"""Tests for ``scripts/preflight_codex_github_footer.py``.

Refs #622.
"""

from __future__ import annotations

import io
import json

import preflight_codex_github_footer as pcgf
import pytest

pytestmark = pytest.mark.shard_preflight

FOOTER = "_Generated by [Codex](https://openai.com/codex) using GPT-5._"


class TestExtractBody:
    def test_string_body_returned(self) -> None:
        assert pcgf.extract_body({"body": "text"}) == "text"

    def test_missing_body_allows_non_post_mutation(self) -> None:
        assert pcgf.extract_body({"title": "Only title"}) is None

    def test_non_string_body_becomes_empty(self) -> None:
        assert pcgf.extract_body({"body": ["text"]}) == ""


class TestResolveModel:
    def test_event_model_wins(self) -> None:
        assert pcgf.resolve_model({"model": "GPT-5"}, {"CODEX_MODEL": "other"}) == "GPT-5"

    def test_metadata_model_used(self) -> None:
        assert pcgf.resolve_model({"metadata": {"model_name": "gpt-5-codex"}}, {}) == "gpt-5-codex"

    def test_env_model_used(self) -> None:
        assert pcgf.resolve_model({}, {"CODEX_GITHUB_FOOTER_MODEL": "GPT-5"}) == "GPT-5"

    def test_missing_model_returns_none(self) -> None:
        assert pcgf.resolve_model({}, {}) is None


class TestDecide:
    def test_issue_body_with_footer_allows(self) -> None:
        out = pcgf.decide(
            "mcp__github__issue_write",
            {"body": f"## Scope\n\nx\n\n{FOOTER}\n"},
            event={"model": "GPT-5"},
        )
        assert out is None

    def test_issue_comment_without_footer_denies(self) -> None:
        out = pcgf.decide(
            "mcp__github__add_issue_comment",
            {"body": "comment"},
            event={"model": "GPT-5"},
        )
        assert out is not None
        reason = out["hookSpecificOutput"]["permissionDecisionReason"]
        assert FOOTER in reason

    def test_pr_body_without_footer_denies(self) -> None:
        out = pcgf.decide(
            "mcp__github__create_pull_request",
            {"body": "## Summary\n\nx"},
            event={"model": "GPT-5"},
        )
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_pr_comment_with_duplicate_footer_denies(self) -> None:
        out = pcgf.decide(
            "mcp__github__add_reply_to_pull_request_comment",
            {"body": f"x\n\n{FOOTER}\n\n{FOOTER}\n"},
            event={"model": "GPT-5"},
        )
        assert out is not None
        reason = out["hookSpecificOutput"]["permissionDecisionReason"]
        assert "multiple" in reason

    def test_review_body_with_footer_allows(self) -> None:
        out = pcgf.decide(
            "mcp__github__pull_request_review_write",
            {"body": f"review\n\n{FOOTER}"},
            event={"metadata": {"model": "GPT-5"}},
        )
        assert out is None

    def test_pending_review_comment_with_footer_allows(self) -> None:
        out = pcgf.decide(
            "mcp__github__add_comment_to_pending_review",
            {"body": f"line note\n\n{FOOTER}"},
            event={"model": "GPT-5"},
        )
        assert out is None

    def test_missing_model_denies(self) -> None:
        out = pcgf.decide(
            "mcp__github__issue_write",
            {"body": f"body\n\n{FOOTER}"},
            event={},
            environ={},
        )
        assert out is not None
        reason = out["hookSpecificOutput"]["permissionDecisionReason"]
        assert "missing trusted model metadata" in reason

    def test_absent_body_allows(self) -> None:
        out = pcgf.decide(
            "mcp__github__update_pull_request",
            {"title": "feat: retitle"},
            event={},
            environ={},
        )
        assert out is None

    @pytest.mark.parametrize(
        "tool_name",
        [
            "mcp__github__list_issues",
            "mcp__github__issue_read",
            "Bash",
        ],
    )
    def test_off_target_tools_allow(self, tool_name: str) -> None:
        out = pcgf.decide(tool_name, {"body": "missing"}, event={})
        assert out is None


class TestMain:
    def _run(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
        payload: str,
    ) -> tuple[int, str, str]:
        monkeypatch.setattr("sys.stdin", io.StringIO(payload))
        rc = pcgf.main([])
        captured = capsys.readouterr()
        return rc, captured.out, captured.err

    def test_valid_event_emits_nothing(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        event = {
            "tool_name": "mcp__github__issue_write",
            "model": "GPT-5",
            "tool_input": {"body": f"body\n\n{FOOTER}"},
        }
        rc, out, err = self._run(monkeypatch, capsys, json.dumps(event))
        assert rc == 0
        assert out == ""
        assert err == ""

    def test_invalid_event_emits_deny_json(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        event = {
            "tool_name": "mcp__github__issue_write",
            "model": "GPT-5",
            "tool_input": {"body": "body"},
        }
        rc, out, err = self._run(monkeypatch, capsys, json.dumps(event))
        assert rc == 0
        decision = json.loads(out)
        assert decision["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert err == ""

    def test_malformed_json_fails_open(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc, out, err = self._run(monkeypatch, capsys, "{not json")
        assert rc == 0
        assert out == ""
        assert "::error::" in err
