"""Tests for ``scripts/preflight_pr_body.py``.

Verifies that the single-command local PR body validator:
* reports every missing required section
* catches Verification command/result pair violations
* catches missing Checklist H3 subsections
* catches missing attribution footer
* catches non-ASCII content
* optionally validates the issue reference when ``--issue`` is given
* passes when the body is fully conformant

Includes test fixtures that use the Codex GitHub connector tool name
(``mcp__codex_apps__github._create_pull_request``) to satisfy the
issue #938 acceptance criterion that tests simulate the actual connector
tool names and prove valid bodies are allowed and invalid bodies are denied
before write.

Refs #938.
"""

from __future__ import annotations

from pathlib import Path

import preflight_pr_body as prb
import preflight_pr_body_required_sections as prs
import preflight_pr_template_shape as pts
import pytest

pytestmark = pytest.mark.shard_preflight


@pytest.fixture(autouse=True)
def _clear_remote_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """Isolate from the ambient CLAUDE_CODE_REMOTE signal (#1025).

    ``main()`` resolves the harness footer relaxation from this var;
    clearing it keeps the default-path tests deterministic regardless of
    where the suite runs (the remote Claude web harness sets it to
    ``true``). Harness-path tests set it explicitly.
    """
    monkeypatch.delenv("CLAUDE_CODE_REMOTE", raising=False)


# ---------------------------------------------------------------------------
# Fixture bodies
# ---------------------------------------------------------------------------

_VERIFICATION_OK = (
    "## Verification\n\n"
    "- command: `uv run python -m pytest -q`\n"
    "  result: `42 passed, exit 0`\n"
)

_CHECKLIST_OK = (
    "## Checklist\n\n"
    "### Bootstrap\n\n"
    "- [ ] facts split honest\n\n"
    "### After-merge (CI)\n\n"
    "- [ ] CI green\n\n"
    "### Post-merge (auto-retro signal)\n\n"
    "- [ ] linked issue closed\n"
)

_FOOTER_OK = "_Generated by [Claude Code](https://claude.ai/code)_\n"

_SECTIONS_OK = (
    "## Facts\n\n- Fact: x\n\n"
    "## Assumptions\n\n- speculation: y\n\n"
    "## Risk and blast radius\n\n- Low\n\n"
    "## Rollback\n\n- `git revert abc1234`\n\n"
)

_RESOURCE_OK = (
    "## Resource Consumption\n\n"
    "- Elapsed (since previous PR or session start): 0:06:42\n"
    "- Total tokens: 230,127\n"
    "- Cost (USD): $0.6396\n"
    "- Model(s): claude-opus-4-8\n\n"
)

_GOOD_BODY = (
    "## Summary\n\nAdd connector PR body preflight.\n\n"
    "## Related Issue\n\nCloses #938\n\n"
    + _SECTIONS_OK
    + _VERIFICATION_OK
    + "\n"
    + _CHECKLIST_OK
    + "\n"
    + _RESOURCE_OK
    + _FOOTER_OK
)


# ---------------------------------------------------------------------------
# TestEvaluate - pure function tests
# ---------------------------------------------------------------------------


class TestEvaluate:
    def test_good_body_returns_no_errors(self) -> None:
        assert prb.evaluate(_GOOD_BODY) == []

    def test_missing_required_section_reported(self) -> None:
        body = _VERIFICATION_OK + "\n" + _CHECKLIST_OK + "\n" + _FOOTER_OK
        errors = prb.evaluate(body)
        assert any("Facts" in e for e in errors), errors

    def test_empty_verification_reported(self) -> None:
        body = (
            _SECTIONS_OK
            + "## Verification\n\n"
            + _CHECKLIST_OK
            + "\n"
            + _FOOTER_OK
        )
        errors = prb.evaluate(body)
        assert any("Verification" in e for e in errors), errors

    def test_verification_pair_required(self) -> None:
        body = (
            _SECTIONS_OK
            + "## Verification\n\nsome text without command pair\n\n"
            + _CHECKLIST_OK
            + "\n"
            + _FOOTER_OK
        )
        errors = prb.evaluate(body)
        assert any("command/result" in e or "Verification" in e for e in errors), errors

    def test_missing_checklist_subsection_reported(self) -> None:
        body = (
            _SECTIONS_OK
            + _VERIFICATION_OK
            + "\n## Checklist\n\n### Bootstrap\n\n- [ ] x\n\n"
            + _FOOTER_OK
        )
        errors = prb.evaluate(body)
        assert any("After-merge" in e for e in errors), errors
        assert any("Post-merge" in e for e in errors), errors

    def test_missing_footer_reported(self) -> None:
        body = _SECTIONS_OK + _VERIFICATION_OK + "\n" + _CHECKLIST_OK
        errors = prb.evaluate(body)
        assert any("footer" in e for e in errors), errors

    def test_non_ascii_body_reported(self) -> None:
        non_ascii_body = _GOOD_BODY.replace("Add connector", "日本語テスト")
        errors = prb.evaluate(non_ascii_body)
        assert any("non-ASCII" in e for e in errors), errors

    def test_non_ascii_ack_suppresses_ascii_check(self) -> None:
        non_ascii_body = _GOOD_BODY + "\n<!-- non-ascii-ack -->\n"
        # Remove ASCII footer and add a non-ASCII sequence, but with ack
        body = non_ascii_body.replace("Add connector", "日本語テスト")
        errors = prb.evaluate(body)
        assert all("non-ASCII" not in e for e in errors), errors

    def test_issue_reference_check_pass(self) -> None:
        errors = prb.evaluate(_GOOD_BODY, issue=938)
        assert all("issue reference" not in e for e in errors), errors

    def test_issue_reference_check_missing(self) -> None:
        body_no_ref = _GOOD_BODY.replace("Closes #938\n", "")
        errors = prb.evaluate(body_no_ref, issue=938)
        assert any("issue reference" in e or "#938" in e for e in errors), errors

    def test_issue_reference_wrong_number(self) -> None:
        errors = prb.evaluate(_GOOD_BODY, issue=999)
        assert any("#999" in e for e in errors), errors

    def test_issue_reference_not_checked_when_none(self) -> None:
        body_no_ref = _GOOD_BODY.replace("Closes #938\n", "")
        errors = prb.evaluate(body_no_ref, issue=None)
        assert all("issue reference" not in e for e in errors), errors

    def test_refs_keyword_satisfies_issue_check(self) -> None:
        body = _GOOD_BODY.replace("Closes #938", "Refs #938")
        errors = prb.evaluate(body, issue=938)
        assert all("#938" not in e or "references" not in e for e in errors), errors

    def test_all_errors_are_ascii(self) -> None:
        body = _SECTIONS_OK + "## Verification\n\nbad\n\n## Checklist\n\nbad\n"
        errors = prb.evaluate(body)
        for e in errors:
            assert e.isascii(), f"error message is not ASCII: {e!r}"

    #; harness_appends_footer path (Claude web harness create, #1025) --

    def test_harness_mode_no_footer_passes(self) -> None:
        body = (
            _SECTIONS_OK + _VERIFICATION_OK + "\n" + _CHECKLIST_OK
            + "\n" + _RESOURCE_OK
        )
        body = (
            "## Summary\n\nx\n\n## Related Issue\n\nCloses #1025\n\n" + body
        )
        errors = prb.evaluate(body, harness_appends_footer=True)
        assert errors == [], errors

    def test_harness_mode_with_footer_rejected(self) -> None:
        errors = prb.evaluate(_GOOD_BODY, harness_appends_footer=True)
        assert any("auto-appends" in e for e in errors), errors


class TestPlaceholderAndSubstantiveContentGates:
    """Checks #7 (placeholder tokens) and #8 (substantive content) in evaluate()."""

    def test_unfilled_angle_token_in_rollback_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Rollback\n\n- `git revert abc1234`\n\n",
            "## Rollback\n\n- git revert <sha>\n\n",
        )
        errors = prb.evaluate(body)
        assert any("<sha>" in e for e in errors), errors

    def test_unfilled_verification_template_token_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            _VERIFICATION_OK,
            "## Verification\n\n- command: `<inline-code>`\n  result: `<result>`\n",
        )
        errors = prb.evaluate(body)
        assert any("<inline-code>" in e for e in errors), errors

    def test_clean_body_no_placeholder_errors(self) -> None:
        errors = prb.evaluate(_GOOD_BODY)
        assert all("<" not in e or "::" in e for e in errors), errors
        assert not any("placeholder" in e for e in errors), errors

    def test_bare_dash_summary_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Summary\n\nAdd connector PR body preflight.\n\n",
            "## Summary\n\n-\n\n",
        )
        errors = prb.evaluate(body)
        assert any("Summary" in e for e in errors), errors

    def test_blank_only_section_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Facts\n\n- Fact: x\n\n",
            "## Facts\n\n\n\n",
        )
        errors = prb.evaluate(body)
        assert any("Facts" in e for e in errors), errors

    def test_html_comment_only_section_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Assumptions\n\n- speculation: y\n\n",
            "## Assumptions\n\n<!-- fill this in -->\n\n",
        )
        errors = prb.evaluate(body)
        assert any("Assumptions" in e for e in errors), errors


class TestUngroundedFactsTimeGate:
    """Check #9 (ungrounded time figures in Facts) in evaluate(). Refs #2198."""

    def test_uncited_time_figure_in_facts_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Facts\n\n- Fact: x\n\n",
            "## Facts\n\n- approx 30-60 seconds CI startup\n\n",
        )
        errors = prb.evaluate(body)
        assert any("ungrounded approximate time figure" in e for e in errors), errors

    def test_cited_time_figure_in_facts_passes(self) -> None:
        body = _GOOD_BODY.replace(
            "## Facts\n\n- Fact: x\n\n",
            "## Facts\n\n- approx 30s startup "
            "(https://github.com/o/r/actions/runs/1)\n\n",
        )
        assert prb.evaluate(body) == []

    def test_time_figure_in_assumptions_not_flagged(self) -> None:
        body = _GOOD_BODY.replace(
            "## Assumptions\n\n- speculation: y\n\n",
            "## Assumptions\n\n- approx 5s in-session creation (Speculation)\n\n",
        )
        assert prb.evaluate(body) == []


class TestHarnessEnvResolution:
    """main() resolves the relaxation from CLAUDE_CODE_REMOTE (#1025)."""

    def test_main_under_harness_accepts_no_footer(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        monkeypatch.setenv("CLAUDE_CODE_REMOTE", "true")
        body = (
            "## Summary\n\nx\n\n## Related Issue\n\nCloses #1025\n\n"
            + _SECTIONS_OK
            + _VERIFICATION_OK
            + "\n"
            + _CHECKLIST_OK
            + "\n"
            + _RESOURCE_OK
        )
        f = tmp_path / "body.md"
        f.write_text(body, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f)])
        captured = capsys.readouterr()
        assert rc == 0, captured.out
        assert "OK" in captured.out

    def test_main_under_harness_rejects_footer(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        monkeypatch.setenv("CLAUDE_CODE_REMOTE", "true")
        f = tmp_path / "body.md"
        f.write_text(_GOOD_BODY, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f)])
        captured = capsys.readouterr()
        assert rc == 1
        assert "auto-appends" in captured.out

    def test_main_without_harness_requires_footer(
        self,
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        # CLAUDE_CODE_REMOTE cleared by autouse fixture.
        body = (
            "## Summary\n\nx\n\n## Related Issue\n\nCloses #1025\n\n"
            + _SECTIONS_OK
            + _VERIFICATION_OK
            + "\n"
            + _CHECKLIST_OK
            + "\n"
            + _RESOURCE_OK
        )
        f = tmp_path / "body.md"
        f.write_text(body, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f)])
        captured = capsys.readouterr()
        assert rc == 1
        assert "footer" in captured.out


# ---------------------------------------------------------------------------
# TestMain - CLI subcommand verify
# ---------------------------------------------------------------------------


class TestMain:
    def test_good_body_exits_0(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        f = tmp_path / "body.md"
        f.write_text(_GOOD_BODY, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f)])
        captured = capsys.readouterr()
        assert rc == 0
        assert "OK" in captured.out

    def test_bad_body_exits_1(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        f = tmp_path / "body.md"
        f.write_text("no sections here", encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f)])
        captured = capsys.readouterr()
        assert rc == 1
        assert "::error::" in captured.out

    def test_issue_flag_pass(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        f = tmp_path / "body.md"
        f.write_text(_GOOD_BODY, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f), "--issue", "938"])
        assert rc == 0

    def test_issue_flag_fail(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        body_no_ref = _GOOD_BODY.replace("Closes #938\n", "")
        f = tmp_path / "body.md"
        f.write_text(body_no_ref, encoding="utf-8")
        rc = prb.main(["verify", "--body-file", str(f), "--issue", "938"])
        captured = capsys.readouterr()
        assert rc == 1
        assert "938" in captured.out


# ---------------------------------------------------------------------------
# TestConnectorToolNames - prove invalid bodies are denied before write
#
# These tests simulate the actual Codex GitHub connector tool names
# (``mcp__codex_apps__github._create_pull_request``) through the existing
# ``preflight_pr_template_shape`` and ``preflight_pr_body_required_sections``
# hooks to satisfy issue #938 acceptance criterion 1 and verification item 1.
# ---------------------------------------------------------------------------

_CODEX_CREATE_PR = "mcp__codex_apps__github._create_pull_request"
_CODEX_UPDATE_PR = "mcp__codex_apps__github._update_pull_request"


class TestConnectorToolInvalidBodyDenied:
    """Prove invalid bodies are denied before the GitHub API write."""

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_missing_required_sections_denies(self, tool_name: str) -> None:
        out = prs.decide(tool_name, {"body": "## Verification\n\nsome text\n"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_missing_verification_pairs_denies(self, tool_name: str) -> None:
        # Has required sections but no Verification command/result pairs.
        body = (
            _SECTIONS_OK
            + "## Verification\n\nno command pairs here\n\n"
            + _CHECKLIST_OK
            + "\n"
            + _FOOTER_OK
        )
        out = pts.decide(tool_name, {"body": body})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_missing_checklist_subsections_denies(self, tool_name: str) -> None:
        body = (
            _SECTIONS_OK
            + _VERIFICATION_OK
            + "\n## Checklist\n\n### Bootstrap\n\n- [ ] x\n\n"
            + _FOOTER_OK
        )
        out = pts.decide(tool_name, {"body": body})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_missing_footer_denies(self, tool_name: str) -> None:
        body = _SECTIONS_OK + _VERIFICATION_OK + "\n" + _CHECKLIST_OK
        out = pts.decide(tool_name, {"body": body})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestConnectorToolValidBodyAllowed:
    """Prove a well-formed body is allowed through the preflight layer.

    Issue #938 verification item 2: "A local test fixture using the same
    tool name [mcp__codex_apps__github._create_pull_request] with a valid
    body is allowed."
    """

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_required_sections_hook_allows_valid_body(self, tool_name: str) -> None:
        out = prs.decide(tool_name, {"body": _GOOD_BODY})
        assert out is None, f"valid body was unexpectedly denied: {out}"

    @pytest.mark.parametrize(
        "tool_name",
        [_CODEX_CREATE_PR, _CODEX_UPDATE_PR],
    )
    def test_template_shape_hook_allows_valid_body(self, tool_name: str) -> None:
        out = pts.decide(tool_name, {"body": _GOOD_BODY})
        assert out is None, f"valid body was unexpectedly denied: {out}"
