"""Codex GitHub connector coverage for the client-side preflight hooks.

Issue #740: the preflight title/body gates only recognized Claude-style
``mcp__github__*`` tool names, so a PR/issue write issued through the
Codex GitHub connector -- which uses the
``mcp__codex_apps__github._<verb>`` naming shape -- slipped past the
client-side gate and was only caught after it had already reached
GitHub. These tests pin the connector-name routing for every preflight
that classifies a call by its tool name, plus the shared canonicalizer.

The companion matcher-surface assertions live in
``tests/test_codex_hooks_config.py`` and
``tests/test_claude_settings_config.py``.
"""

from __future__ import annotations

import _github_tool_names as gtn
import pr_body_close_keyword_gate as pck
import preflight_codex_github_footer as pcgf
import preflight_non_ascii as pna
import preflight_pr_body_required_sections as prs
import preflight_pr_template_shape as pts
import preflight_title_policy as ptp
import pytest

pytestmark = pytest.mark.shard_preflight

# Codex GitHub connector tool names (issue #740 Facts).
CODEX_CREATE_PR = "mcp__codex_apps__github._create_pull_request"
CODEX_UPDATE_PR = "mcp__codex_apps__github._update_pull_request"
CODEX_CREATE_ISSUE = "mcp__codex_apps__github._create_issue"

FOOTER = "_Generated by [Codex](https://openai.com/codex) using GPT-5._"


class TestCanonicalGithubTool:
    @pytest.mark.parametrize(
        ("connector", "canonical"),
        [
            (CODEX_CREATE_PR, "mcp__github__create_pull_request"),
            (CODEX_UPDATE_PR, "mcp__github__update_pull_request"),
            (CODEX_CREATE_ISSUE, "mcp__github__issue_write"),
        ],
    )
    def test_connector_names_map_to_claude_names(
        self, connector: str, canonical: str
    ) -> None:
        assert gtn.canonical_github_tool(connector) == canonical

    @pytest.mark.parametrize(
        "name",
        [
            "mcp__github__create_pull_request",
            "mcp__github__issue_write",
            "Bash",
            "mcp__codex_apps__github._unknown_tool",
        ],
    )
    def test_unknown_names_pass_through_unchanged(self, name: str) -> None:
        assert gtn.canonical_github_tool(name) == name


class TestTitlePolicyConnectorRouting:
    def test_connector_pr_invalid_title_denies(self) -> None:
        out = ptp.decide(CODEX_CREATE_PR, {"title": "not a conventional title"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"
        # The deny reason quotes the real connector tool name, not the alias.
        assert CODEX_CREATE_PR in out["hookSpecificOutput"]["permissionDecisionReason"]

    def test_connector_pr_non_ascii_title_denies(self) -> None:
        out = ptp.decide(CODEX_CREATE_PR, {"title": "fix(hooks): 日本語"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_connector_issue_invalid_title_denies(self) -> None:
        out = ptp.decide(CODEX_CREATE_ISSUE, {"title": "no type prefix here"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_connector_pr_valid_title_allows(self) -> None:
        assert ptp.decide(CODEX_CREATE_PR, {"title": "fix(hooks): cover codex connector"}) is None

    def test_kind_for_tool_maps_connector_names(self) -> None:
        assert ptp.kind_for_tool(CODEX_CREATE_PR) == "pull_request"
        assert ptp.kind_for_tool(CODEX_UPDATE_PR) == "pull_request"
        assert ptp.kind_for_tool(CODEX_CREATE_ISSUE) == "issue"


class TestNonAsciiConnectorRouting:
    def test_connector_pr_non_ascii_body_denies(self) -> None:
        out = pna.decide(CODEX_CREATE_PR, {"title": "fix(x): y", "body": "こんにちは"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert CODEX_CREATE_PR in out["hookSpecificOutput"]["permissionDecisionReason"]

    def test_connector_pr_ascii_body_allows(self) -> None:
        assert pna.decide(CODEX_CREATE_PR, {"title": "fix(x): y", "body": "plain ascii body"}) is None


class TestRequiredSectionsConnectorRouting:
    def test_connector_pr_missing_sections_denies(self) -> None:
        out = prs.decide(CODEX_CREATE_PR, {"body": "## Facts\n\nonly one section\n"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert CODEX_CREATE_PR in out["hookSpecificOutput"]["permissionDecisionReason"]


class TestTemplateShapeConnectorRouting:
    def test_connector_pr_bad_shape_denies(self) -> None:
        out = pts.decide(CODEX_CREATE_PR, {"body": "## Summary\n\nno verification or checklist shape\n"})
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestCloseKeywordConnectorRouting:
    def test_connector_pr_refs_only_non_tracking_denies(self) -> None:
        out = pck.decide(
            CODEX_CREATE_PR,
            {"body": "Refs #5", "owner": "tvna", "repo": "claude-md"},
            token_getter=lambda: "token",
            label_getter=lambda _o, _r, _n: ["type:fix"],
        )
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert CODEX_CREATE_PR in out["hookSpecificOutput"]["permissionDecisionReason"]


class TestCodexFooterConnectorRouting:
    def test_connector_pr_missing_footer_denies(self) -> None:
        out = pcgf.decide(
            CODEX_CREATE_PR,
            {"body": "## Summary\n\nx"},
            event={"model": "GPT-5"},
        )
        assert out is not None
        assert out["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_connector_issue_with_footer_allows(self) -> None:
        out = pcgf.decide(
            CODEX_CREATE_ISSUE,
            {"body": f"## Scope\n\nx\n\n{FOOTER}\n"},
            event={"model": "GPT-5"},
        )
        assert out is None
