"""Tests for ``scripts/pr_body_builder.py``.

Verifies that the template-fill helper emits a PR body skeleton that:
* contains all required H2 sections (body_policy baseline gate)
* has a non-empty Verification command/result pair (post-2026-05-26 shape)
* has all three Checklist H3 subsections
* carries an agent attribution footer
* is ASCII-only
* references the supplied issue number

Refs #938.
"""

from __future__ import annotations

from pathlib import Path

import pr_body_builder as builder
import pytest
from body_policy import (
    missing_sections,
    required_sections,
    verify_pr_agent_attribution_footer,
    verify_pr_checklist_subsections,
    verify_pr_verification_pairs,
)

pytestmark = pytest.mark.shard_preflight


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ISSUE = 938
_SESSION_URL = "https://claude.ai/code/session_test"
_CODEX_MODEL = "gpt-4o"


def _default_body() -> str:
    return builder.build(_ISSUE)


def _claude_body(session_url: str = _SESSION_URL) -> str:
    return builder.build(_ISSUE, agent="Claude Code", session_url=session_url)


def _codex_body(model: str = _CODEX_MODEL) -> str:
    return builder.build(_ISSUE, agent="Codex", model=model)


# ---------------------------------------------------------------------------
# TestBuild - structural and content checks on the built body
# ---------------------------------------------------------------------------


class TestBuild:
    def test_closes_issue_reference_present(self) -> None:
        body = _default_body()
        assert f"Closes #{_ISSUE}" in body

    def test_required_sections_all_present(self) -> None:
        body = _default_body()
        required = required_sections("pull_request", body=body)
        from body_policy import extract_headings, missing_sections

        missing = missing_sections(required, extract_headings(body))
        assert missing == [], missing

    def test_verification_pair_present(self) -> None:
        body = _default_body()
        assert verify_pr_verification_pairs(body) == []

    def test_checklist_subsections_present(self) -> None:
        body = _default_body()
        assert verify_pr_checklist_subsections(body) == []

    def test_attribution_footer_present(self) -> None:
        body = _default_body()
        assert verify_pr_agent_attribution_footer(body) == []

    def test_body_is_ascii_only(self) -> None:
        body = _default_body()
        assert body.isascii(), "builder output must be ASCII-only for GitHub posts"

    def test_no_html_comments_in_output(self) -> None:
        body = _default_body()
        assert "<!--" not in body, "HTML comments should be stripped from builder output"

    def test_claude_code_footer(self) -> None:
        body = _claude_body()
        assert "_Generated by [Claude Code](" in body

    def test_custom_session_url_in_footer(self) -> None:
        url = "https://claude.ai/code/session_abc123"
        body = builder.build(_ISSUE, agent="Claude Code", session_url=url)
        assert url in body

    def test_codex_footer_with_model(self) -> None:
        body = _codex_body()
        assert "_Generated by [Codex](https://openai.com/codex) using gpt-4o._" in body

    def test_codex_requires_model(self) -> None:
        with pytest.raises(ValueError, match="requires --model"):
            builder.build(_ISSUE, agent="Codex", model=None)

    def test_different_issue_numbers(self) -> None:
        for issue in (1, 42, 100, 9999):
            body = builder.build(issue)
            assert f"Closes #{issue}" in body

    def test_body_ends_with_newline(self) -> None:
        body = _default_body()
        assert body.endswith("\n")

    def test_no_empty_backtick_verification(self) -> None:
        body = _default_body()
        assert "``\n  result: ``" not in body, (
            "empty backtick verification placeholder must be replaced"
        )


# ---------------------------------------------------------------------------
# TestBuiltBodyPassesBodyPolicy - integration with body_policy.py
# ---------------------------------------------------------------------------


class TestBuiltBodyPassesBodyPolicy:
    """Ensure the builder output passes all body_policy checks in one pass.

    These tests mirror what ``scripts/preflight_pr_body.py verify`` does so
    a first-attempt green CI run is achievable without editing the body post-
    creation. Refs #938 acceptance criterion 4.
    """

    @pytest.mark.parametrize(
        ("agent", "kwargs"),
        [
            ("Claude Code", {"session_url": "https://claude.ai/code"}),
            ("Codex", {"model": "gpt-4o"}),
        ],
    )
    def test_passes_all_policy_checks(
        self, agent: str, kwargs: dict
    ) -> None:
        body = builder.build(_ISSUE, agent=agent, **kwargs)
        assert missing_sections(
            required_sections("pull_request", body=body), []
        ) == list(required_sections("pull_request", body=body)), (
            "headings not checked in isolation -- check via extract_headings"
        )
        from body_policy import extract_headings

        missing = missing_sections(
            required_sections("pull_request", body=body),
            extract_headings(body),
        )
        assert missing == []
        assert verify_pr_verification_pairs(body) == []
        assert verify_pr_checklist_subsections(body) == []
        assert verify_pr_agent_attribution_footer(body) == []


# ---------------------------------------------------------------------------
# TestMain - CLI interface
# ---------------------------------------------------------------------------


class TestMain:
    def test_build_writes_body_to_stdout(self, capsys: pytest.CaptureFixture[str]) -> None:
        rc = builder.main(["build", "--issue", str(_ISSUE)])
        captured = capsys.readouterr()
        assert rc == 0
        assert f"Closes #{_ISSUE}" in captured.out
        assert captured.err == ""

    def test_build_with_agent_and_url(self, capsys: pytest.CaptureFixture[str]) -> None:
        rc = builder.main(
            [
                "build",
                "--issue", str(_ISSUE),
                "--agent", "Claude Code",
                "--session-url", _SESSION_URL,
            ]
        )
        captured = capsys.readouterr()
        assert rc == 0
        assert _SESSION_URL in captured.out

    def test_codex_build_with_model(self, capsys: pytest.CaptureFixture[str]) -> None:
        rc = builder.main(
            [
                "build",
                "--issue", str(_ISSUE),
                "--agent", "Codex",
                "--model", _CODEX_MODEL,
            ]
        )
        captured = capsys.readouterr()
        assert rc == 0
        assert "Codex" in captured.out
        assert _CODEX_MODEL in captured.out

    def test_codex_without_model_exits_1(self, capsys: pytest.CaptureFixture[str]) -> None:
        rc = builder.main(["build", "--issue", str(_ISSUE), "--agent", "Codex"])
        captured = capsys.readouterr()
        assert rc == 1
        assert "requires --model" in captured.err

    def test_custom_template_path(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        # A minimal template with the placeholders the builder replaces.
        tmpl = tmp_path / "tpl.md"
        tmpl.write_text(
            "## Facts\n\n-\n\n## Assumptions\n\n-\n\n"
            "## Risk and blast radius\n\n-\n\n## Rollback\n\n-\n\n"
            "## Verification\n\n- command: ``\n  result: ``\n\n"
            "## Checklist\n\n### Bootstrap\n\n- [ ] x\n\n"
            "### After-merge\n\n- [ ] y\n\n"
            "### Post-merge\n\n- [ ] z\n\n"
            "Closes #\n\n"
            "_Generated by [Agent Name](agent-session-url)_\n",
            encoding="utf-8",
        )
        rc = builder.main(
            ["build", "--issue", str(_ISSUE), "--template", str(tmpl)]
        )
        captured = capsys.readouterr()
        assert rc == 0
        assert f"Closes #{_ISSUE}" in captured.out
        assert "_Generated by [Claude Code](" in captured.out
