#!/usr/bin/env bash
#
# Devcontainer DNS proxy controller (best-effort egress aid, NOT a sandbox).
#
# Points /etc/resolv.conf at a local dnsmasq that forwards ONLY allowlisted
# domains upstream and adds each resolved IP to the `allowed-egress` ipset, so a
# companion iptables rule can permit egress to exactly those IPs. Driven by the
# same .devcontainer/network/*.allowlist single source as apply-egress-allowlist.sh
# (host enumeration reuses read_allowlist from _egress-lib.sh, so the bash and
# Python parsers stay in agreement via scan_allowlist_parser_parity.py).
#
# Honest limitation: the agent holds NET_ADMIN and can revert /etc/resolv.conf,
# kill dnsmasq, or flush the ipset (CVE-2025-32955 class bypass). This is
# detection plus best-effort blocking, not an enforcement boundary. See
# docs/runbooks/devcontainers.md.
#
# Default OFF: `start` and `stop` are no-ops unless EGRESS_DNS_PROXY=1.
#
# Subcommands:
#   generate-config <allowlist-file> [--upstream <ip>]... [--ipset-name <name>]
#       Pure stdout. No root, no kernel calls, no file writes. Unit-testable seam.
#   start <allowlist-file>   Apply the proxy (gated by EGRESS_DNS_PROXY=1; root).
#   stop                     Tear down and restore resolv.conf (idempotent).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=.devcontainer/scripts/_egress-lib.sh
source "$SCRIPT_DIR/_egress-lib.sh"

# Overridable for tests; default to the real container paths.
RESOLV_CONF="${RESOLV_CONF:-/etc/resolv.conf}"
RESOLV_BACKUP="${RESOLV_BACKUP:-/etc/resolv.conf.egress-backup}"
DNSMASQ_CONF="${DNSMASQ_CONF:-/etc/dnsmasq.d/egress.conf}"
IPSET_NAME_DEFAULT="allowed-egress"

usage() {
  cat >&2 <<'EOF'
usage:
  _egress-dnsproxy.sh generate-config <allowlist-file> [--upstream <ip>]... [--ipset-name <name>]
  _egress-dnsproxy.sh start <allowlist-file>
  _egress-dnsproxy.sh stop
EOF
}

# Read nameserver IPs from a given resolv.conf-shaped file (de-duplicated).
read_nameservers_from() {
  awk '/^nameserver[[:space:]]+/ { print $2 }' "$1" | sort -u
}

# Emit a dnsmasq config to stdout from an allowlist file. Deterministic: hosts
# are sorted/unique, upstreams keep their given order. Reads only the allowlist
# (and, if no --upstream is supplied, the backup/live resolv.conf to discover an
# upstream); writes nothing and needs no privileges.
cmd_generate_config() {
  local allowlist="" ipset_name="$IPSET_NAME_DEFAULT"
  local -a upstreams=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --upstream)
        [[ $# -ge 2 ]] || { echo "--upstream requires a value" >&2; return 64; }
        upstreams+=("$2")
        shift 2
        ;;
      --ipset-name)
        [[ $# -ge 2 ]] || { echo "--ipset-name requires a value" >&2; return 64; }
        ipset_name="$2"
        shift 2
        ;;
      --*)
        echo "unknown option: $1" >&2
        return 64
        ;;
      *)
        if [[ -z "$allowlist" ]]; then
          allowlist="$1"
          shift
        else
          echo "unexpected argument: $1" >&2
          return 64
        fi
        ;;
    esac
  done

  if [[ -z "$allowlist" ]]; then
    echo "generate-config requires <allowlist-file>" >&2
    return 64
  fi
  if [[ ! -f "$allowlist" ]]; then
    echo "allowlist file not found: $allowlist" >&2
    return 66
  fi

  if [[ "${#upstreams[@]}" -eq 0 ]]; then
    local src="$RESOLV_CONF"
    [[ -f "$RESOLV_BACKUP" ]] && src="$RESOLV_BACKUP"
    local ns
    while IFS= read -r ns; do
      upstreams+=("$ns")
    done < <(read_nameservers_from "$src")
  fi
  if [[ "${#upstreams[@]}" -eq 0 ]]; then
    echo "no upstream DNS available (pass --upstream or populate $RESOLV_CONF)" >&2
    return 69
  fi

  local -a hosts=()
  mapfile -t hosts < <(read_allowlist "$allowlist" | sort -u)
  if [[ "${#hosts[@]}" -eq 0 ]]; then
    echo "allowlist is empty: $allowlist" >&2
    return 78
  fi

  printf '# Generated by _egress-dnsproxy.sh -- DO NOT EDIT.\n'
  printf '# Source: %s\n' "$allowlist"
  printf '# ipset: %s\n' "$ipset_name"
  printf 'no-resolv\n'
  local up host
  for up in "${upstreams[@]}"; do
    printf 'server=%s\n' "$up"
  done
  for host in "${hosts[@]}"; do
    printf '\n'
    for up in "${upstreams[@]}"; do
      printf 'server=/%s/%s\n' "$host" "$up"
    done
    printf 'ipset=/%s/%s\n' "$host" "$ipset_name"
  done
}

# Capture the genuine original resolv.conf exactly once per start/stop cycle.
# Re-run safety: if a backup already exists it holds the REAL original, so we
# never clobber it with the already-rewritten (127.0.0.1) file.
backup_resolv_conf() {
  if [[ -e "$RESOLV_BACKUP" ]]; then
    return 0
  fi
  if grep -qE '^[[:space:]]*nameserver[[:space:]]+127\.0\.0\.1[[:space:]]*$' "$RESOLV_CONF" \
    && [[ "$(grep -cE '^[[:space:]]*nameserver' "$RESOLV_CONF")" -eq 1 ]]; then
    echo "refusing to back up an already-rewritten resolv.conf with no real upstream" >&2
    return 70
  fi
  cp -p "$RESOLV_CONF" "$RESOLV_BACKUP"
}

cmd_start() {
  local allowlist="${1:-}"
  if [[ -z "$allowlist" ]]; then
    echo "start requires <allowlist-file>" >&2
    return 64
  fi

  if [[ "${EGRESS_DNS_PROXY:-0}" != "1" ]]; then
    echo "EGRESS_DNS_PROXY!=1; DNS proxy disabled (opt-in no-op)." >&2
    return 0
  fi

  require_command dnsmasq || exit $?
  require_command ipset || exit $?

  if [[ "$(id -u)" -ne 0 ]]; then
    echo "DNS proxy must run as root" >&2
    return 77
  fi

  # 1. ensure the egress ipset exists (idempotent).
  ipset create "$IPSET_NAME_DEFAULT" hash:ip -exist

  # 2. back up the original resolv.conf (idempotent, re-run safe).
  backup_resolv_conf

  # 3. derive upstreams from the backup (the genuine original), never the live
  #    file, so a re-run never points dnsmasq at itself (127.0.0.1) -> loop.
  local -a upstreams=()
  local ns
  while IFS= read -r ns; do
    upstreams+=("$ns")
  done < <(read_nameservers_from "$RESOLV_BACKUP")
  if [[ "${#upstreams[@]}" -eq 0 ]]; then
    echo "no upstream nameserver found in $RESOLV_BACKUP" >&2
    return 69
  fi

  # 4. generate the dnsmasq config from the allowlist + derived upstreams.
  mkdir -p "$(dirname "$DNSMASQ_CONF")"
  local -a genargs=("$allowlist")
  for ns in "${upstreams[@]}"; do
    genargs+=(--upstream "$ns")
  done
  cmd_generate_config "${genargs[@]}" >"$DNSMASQ_CONF"

  # 5. point the system resolver at the local dnsmasq.
  printf 'nameserver 127.0.0.1\n' >"$RESOLV_CONF"

  # 6. launch dnsmasq from ONLY the generated config (no global /etc/dnsmasq.*).
  dnsmasq --conf-file="$DNSMASQ_CONF"
  echo "started DNS proxy from $allowlist (ipset=$IPSET_NAME_DEFAULT)"
}

cmd_stop() {
  if [[ "${EGRESS_DNS_PROXY:-0}" != "1" ]]; then
    echo "EGRESS_DNS_PROXY!=1; DNS proxy disabled (opt-in no-op)." >&2
    return 0
  fi

  if [[ "$(id -u)" -ne 0 ]]; then
    echo "DNS proxy must run as root" >&2
    return 77
  fi

  # Stop the proxy started from our generated config (best-effort, idempotent).
  if command -v pkill >/dev/null 2>&1; then
    pkill -f "dnsmasq --conf-file=$DNSMASQ_CONF" || true
  fi

  # Restore the original resolv.conf and consume the backup so the next start
  # re-captures a real original. No backup -> clean no-op.
  if [[ -e "$RESOLV_BACKUP" ]]; then
    cp -p "$RESOLV_BACKUP" "$RESOLV_CONF"
    rm -f "$RESOLV_BACKUP"
    echo "restored $RESOLV_CONF from backup"
  else
    echo "no resolv.conf backup to restore (no-op)"
  fi
}

main() {
  local subcmd="${1:-}"
  [[ $# -gt 0 ]] && shift
  case "$subcmd" in
    generate-config) cmd_generate_config "$@" ;;
    start) cmd_start "$@" ;;
    stop) cmd_stop "$@" ;;
    -h | --help | help) usage ;;
    *)
      usage
      return 64
      ;;
  esac
}

main "$@"
