#!/usr/bin/env python3
"""Verify that issue and PR bodies contain their template's required sections.

The workflow ``.github/workflows/verify-body-policy.yml`` shells out to
this module.

Contract:
- Inputs: the ``verify`` subcommand; ``--kind``; the body from
  ``--body-file`` or the ``ISSUE_BODY`` / ``PR_BODY`` env var; the author
  login and ``--created-at`` / ``--cutoff`` skip thresholds.
- Outputs: ``::error::`` annotations naming each missing section on
  stdout; exit 0 when every required section is present (or a skip
  applies), exit 1 otherwise.
- Failure policy: fails loud per CLAUDE.md section 4 (gate: a body
  missing a required section exits non-zero).

The detailed contract is:

* Read the body from ``--body-file`` when supplied, otherwise from the
  ``ISSUE_BODY`` or ``PR_BODY`` env var (whichever matches ``--kind``).
* Strip HTML comments before parsing (delegating to
  ``issue_link.strip_html_comments`` so the regex stays single-sourced).
* Extract every ``## Heading`` and ``### Heading`` line; lower-level
  headings are ignored to keep PR template H2 and Issue Forms H3
  rendering both passing.
* Require a fixed list of section headings per kind. For issues a
  tracking-shaped body (presence of ``Initial child issues``) swaps to
  the tracking-template required set; otherwise the common baseline
  shared by feat/fix/refactor/docs/chore/generic forms applies.
* Skip trusted bot authors (see ``_trusted_bots._TRUSTED_BOT_LOGINS``).
* Skip events whose ``--created-at`` predates ``--cutoff`` so the
  back-catalog is not retro-failed when the gate lands.
* Exit 0 when every required section is present (or when a skip
  applies); exit 1 otherwise. ``::error::`` annotations surface
  individual missing sections in the GitHub Actions UI.

Tested by ``tests/test_body_policy.py``. Refs #205.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

from _trusted_bots import _TRUSTED_BOT_LOGINS
from issue_link import strip_html_comments

_HEADING_RE = re.compile(r"^(#{2,3})[ \t]+(.+?)[ \t]*$", re.MULTILINE)
_TRAILING_COLON_RE = re.compile(r":+\s*$")
_AMPERSAND_RE = re.compile(r"\s*&\s*")
_TRACKING_MARKER = "Initial child issues"

_PR_REQUIRED: tuple[str, ...] = (
    "Summary",
    "Related Issue",
    "Facts",
    "Assumptions",
    "Risk and blast radius",
    "Rollback",
    "Verification",
    "Checklist",
    "Resource Consumption",
)
# ``Text delta`` appears only when the diff touches universal instruction
# text (.apm/instructions/**, CLAUDE.md, AGENTS.md), so it is allowlisted,
# not required. A PR body may carry no H2 outside ``_PR_ALLOWED`` (see
# :func:`unexpected_pr_sections`). ``Summary`` leads as the conclusion-first
# (BLUF) block; ``Related Issue`` is required for parity with the CLAUDE.md
# section 3 / ``issue_link.py`` ``Refs/Closes #N`` rule. Refs #1396.
_PR_OPTIONAL: tuple[str, ...] = ("Text delta",)
_PR_ALLOWED: tuple[str, ...] = _PR_REQUIRED + _PR_OPTIONAL
_ISSUE_COMMON_REQUIRED: tuple[str, ...] = (
    "Scope",
    "Facts",
    "Proposed work",
    "Verification",
    "Acceptance criteria",
)
_ISSUE_TRACKING_REQUIRED: tuple[str, ...] = (
    "Scope",
    "Facts",
    "Initial child issues",
    "Completion criteria",
)
# Issue sections allowed but not required. ``Parent`` links the umbrella
# tracking issue and is omitted when the issue is standalone, so it is
# documented in the standard doc's section list yet cannot be required.
# It is the single source the standard-doc sync test uses to reconcile the
# doc's issue list with the required constants. Refs #1191, #1396.
_ISSUE_OPTIONAL: tuple[str, ...] = ("Parent",)

# Shape gate constants (PR template post-2026-05-26). The hook
# (scripts/preflight_pr_template_shape.py) imports these so the
# client-side and server-side checks cannot drift.
_VERIFICATION_HEADING = "Verification"
_CHECKLIST_HEADING = "Checklist"
_CHECKLIST_SUBSECTIONS: tuple[str, ...] = (
    "Bootstrap",
    "After-merge",
    "Post-merge",
)

_VERIFICATION_COMMAND_RE = re.compile(
    r"^-[ \t]+command:[ \t]*`[^`\n]+`[ \t]*$",
    re.MULTILINE,
)
# A command line that is well-formed up to the closing backtick but
# carries trailing non-whitespace after it (e.g. ``(pre-push hooks)``).
# Detected only to emit a targeted deny reason -- such a line already
# fails _VERIFICATION_COMMAND_RE, so this never widens what passes.
# Recurring author defect: retro #1054 row 2(a), retro #1376 repair 2.
_VERIFICATION_COMMAND_TRAILING_RE = re.compile(
    r"^-[ \t]+command:[ \t]*`[^`\n]+`[ \t]*(?P<trailing>\S.*)$",
)
_VERIFICATION_RESULT_RE = re.compile(
    r"^[ \t]{2}result:[ \t]*\S.*$",
    re.MULTILINE,
)
_CHECKLIST_ITEM_RE = re.compile(
    r"^[ \t]*-[ \t]+\[[ xX]\][ \t]+.+$",
    re.MULTILINE,
)
_AGENT_ATTRIBUTION_FOOTER_RE = re.compile(
    r"_Generated by \[[^\]\n]+\]\([A-Za-z][A-Za-z0-9+.-]*://[^)\s]+\)"
    r"(?: using [ -~]+)?_"
)
_BARE_DASH_RE = re.compile(r"^-\s*$")
_CODEX_AGENT_NAME = "Codex"
_CODEX_AGENT_URL = "https://openai.com/codex"
_CODEX_FOOTER_PREFIX = (
    f"_Generated by [{_CODEX_AGENT_NAME}]({_CODEX_AGENT_URL}) using "
)
_CODEX_FOOTER_RE = re.compile(
    r"_Generated by \[Codex\]\(https://openai\.com/codex\) using ([ -~]+)\._"
)


def extract_headings(body: str) -> list[tuple[int, str]]:
    """Return ``(level, text)`` tuples for every H2/H3 heading in *body*.

    HTML-commented headings are not returned. Trailing whitespace is
    stripped from the heading text; trailing colons are removed so that
    ``## Scope:`` and ``## Scope`` match the same required key.
    """
    cleaned = strip_html_comments(body.replace("\r", ""))
    out: list[tuple[int, str]] = []
    for match in _HEADING_RE.finditer(cleaned):
        level = len(match.group(1))
        text = _TRAILING_COLON_RE.sub("", match.group(2)).strip()
        # MCP write tools (create_pull_request / update_pull_request) HTML-encode
        # & as &amp; before storing. Decode here so "Risk &amp; blast radius"
        # matches the required "Risk & blast radius" entry. Refs #892.
        text = html.unescape(text)
        if text:
            out.append((level, text))
    return out


def required_sections(kind: str, *, body: str) -> tuple[str, ...]:
    """Return the section list to enforce for *kind* and *body*."""
    if kind == "pull_request":
        return _PR_REQUIRED
    if kind == "issue":
        cleaned = strip_html_comments(body.replace("\r", ""))
        if _TRACKING_MARKER.lower() in cleaned.lower():
            return _ISSUE_TRACKING_REQUIRED
        return _ISSUE_COMMON_REQUIRED
    raise ValueError(f"unsupported body kind: {kind!r}")


def _normalize_heading(text: str) -> str:
    """Return a form that treats ``&`` and ``and`` as interchangeable.

    The single substitution makes the canonical required-section name
    ``Risk and blast radius`` also accept the legacy ``Risk & blast radius``
    spelling without changing letter case or other whitespace inside the heading.
    Refs #332: AI agents rendered the heading in prose form on first
    attempt; #912 made ``and`` the canonical default to avoid HTML-encoding
    of ``&`` by ``mcp__github__create_pull_request``.
    """
    return _AMPERSAND_RE.sub(" and ", text).strip()


def missing_sections(
    required: tuple[str, ...] | list[str],
    headings: list[tuple[int, str]],
) -> list[str]:
    """Return required entries not present in *headings*.

    Matching is case-sensitive (so ``facts`` still does not satisfy
    ``Facts``), but ``&`` and ``and`` are treated as equivalent: a body
    that writes ``## Risk & blast radius`` satisfies the canonical
    ``Risk and blast radius`` slot, and vice versa.
    """
    present = {_normalize_heading(text) for _, text in headings}
    return [
        name
        for name in required
        if _normalize_heading(name) not in present
    ]


def unexpected_pr_sections(
    headings: list[tuple[int, str]],
) -> list[str]:
    """Return level-2 PR heading texts that fall outside ``_PR_ALLOWED``.

    Only H2 headings are allowlisted; the Checklist's H3 subsections are
    part of their parent section and are skipped. Matching reuses
    :func:`_normalize_heading` (``&``/``and`` equivalent, case significant).
    Offenders are returned in document order, de-duplicated. Refs #1396.
    """
    allowed = {_normalize_heading(name) for name in _PR_ALLOWED}
    seen: set[str] = set()
    out: list[str] = []
    for level, text in headings:
        if level != 2:
            continue
        norm = _normalize_heading(text)
        if norm in allowed or norm in seen:
            continue
        seen.add(norm)
        out.append(text)
    return out


def verify_pr_allowed_sections(body: str) -> list[str]:
    """Return ``::error::`` strings for PR H2 headings outside the allowlist.

    Single source of the allowlist deny message so the server gate
    (:func:`_verify`) and the client hook
    (``scripts/preflight_pr_template_shape.py``) cannot drift. Returns
    ``[]`` when every H2 heading is in ``_PR_ALLOWED``. Refs #1396.
    """
    allowed_list = ", ".join(_PR_ALLOWED)
    return [
        f"::error::pull_request body has an H2 section outside the allowed "
        f"set: ## {name}. Allowed H2 headings: {allowed_list}."
        for name in unexpected_pr_sections(extract_headings(body))
    ]


def extract_section_body(body: str, heading: str, level: int = 2) -> str:
    """Return the text between ``<level> heading`` and the next sibling H2.

    The H2 sibling boundary is intentional: a section's H3 subsections
    are part of the section and are kept in the returned slice. HTML
    comments are stripped before slicing so a commented heading does not
    pretend to terminate the range.

    Returns ``""`` when *heading* is absent. Matching is case-insensitive
    and tolerates trailing colons and whitespace (mirrors
    :func:`extract_headings`). Heading text comparison is normalized via
    :func:`_normalize_heading` so ``Risk and blast radius`` and ``Risk &
    blast radius`` map to the same slot.
    """
    cleaned = strip_html_comments(body.replace("\r", ""))
    target = _normalize_heading(heading).casefold()
    lines = cleaned.splitlines()
    start_idx: int | None = None
    end_idx = len(lines)
    pattern = re.compile(r"^(#{2,3})[ \t]+(.+?)[ \t]*$")
    for i, line in enumerate(lines):
        match = pattern.match(line)
        if match is None:
            continue
        line_level = len(match.group(1))
        text = _TRAILING_COLON_RE.sub("", match.group(2)).strip()
        norm = _normalize_heading(text).casefold()
        if start_idx is None:
            if line_level == level and norm == target:
                start_idx = i + 1
            continue
        if line_level <= 2:
            end_idx = i
            break
    if start_idx is None:
        return ""
    return "\n".join(lines[start_idx:end_idx])


def verify_pr_verification_pairs(body: str) -> list[str]:
    """Return list of ``::error::`` strings for the Verification section.

    The post-2026-05-26 PR shape requires the ``## Verification`` section
    to contain at least one ``- command: \\`...\\``` line each immediately
    followed by a ``  result: ...`` line. Pairing is order-dependent: a
    command without its result on the next line fails, and a result
    without a preceding command on the previous line fails.

    Returns ``[]`` when the section is well-formed.
    """
    section = extract_section_body(body, _VERIFICATION_HEADING)
    if not section.strip():
        return [
            "::error::Verification section is empty. Provide at least "
            "one '- command: `...`' line paired with '  result: ...' on "
            "the next line (post-2026-05-26 PR shape)."
        ]
    lines = section.splitlines()
    pairs = 0
    errors: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        cmd_match = _VERIFICATION_COMMAND_RE.fullmatch(line)
        if cmd_match is not None:
            if i + 1 >= len(lines) or _VERIFICATION_RESULT_RE.fullmatch(
                lines[i + 1]
            ) is None:
                errors.append(
                    "::error::Verification 'command:' line not followed "
                    "by a '  result: ...' line (post-2026-05-26 PR shape)."
                )
                i += 1
                continue
            pairs += 1
            i += 2
            continue
        trailing_match = _VERIFICATION_COMMAND_TRAILING_RE.fullmatch(line)
        if trailing_match is not None:
            trailing = trailing_match.group("trailing")
            errors.append(
                "::error::Verification 'command:' line has trailing text "
                f"{trailing!r} after the closing backtick; the command "
                "line must be code-only. Move the note onto the "
                "'  result: ...' line or drop it (post-2026-05-26 PR "
                "shape)."
            )
            # Consume an immediately-following result line so it is not
            # also flagged as an orphan -- the trailing-text error is the
            # single actionable signal.
            if i + 1 < len(lines) and _VERIFICATION_RESULT_RE.fullmatch(
                lines[i + 1]
            ):
                i += 2
            else:
                i += 1
            continue
        res_match = _VERIFICATION_RESULT_RE.fullmatch(line)
        if res_match is not None:
            errors.append(
                "::error::Verification 'result:' line without a preceding "
                "'- command: `...`' line on the previous line "
                "(post-2026-05-26 PR shape)."
            )
        i += 1
    if pairs == 0 and not errors:
        errors.append(
            "::error::Verification section has no command/result pairs. "
            "Add at least one '- command: `...`' followed by "
            "'  result: ...' (post-2026-05-26 PR shape)."
        )
    return errors


def verify_pr_checklist_subsections(body: str) -> list[str]:
    """Return list of ``::error::`` strings for the Checklist section.

    The post-2026-05-26 PR shape requires the ``## Checklist`` section
    to contain three H3 subsections (``Bootstrap``, ``After-merge``,
    ``Post-merge``), each with at least one ``- [ ]`` or ``- [x]`` item.
    Subsection names are matched case-insensitively after stripping a
    trailing parenthetic clarifier (``After-merge (CI)`` -> ``After-merge``)
    so authors can clarify the heading in prose.

    Returns ``[]`` when the structure is well-formed.
    """
    section = extract_section_body(body, _CHECKLIST_HEADING)
    if not section.strip():
        return [
            "::error::Checklist section is empty. The post-2026-05-26 PR "
            "shape requires three H3 subsections: ### Bootstrap, "
            "### After-merge, ### Post-merge."
        ]
    lines = section.splitlines()
    found: dict[str, int] = {}
    pattern = re.compile(r"^###[ \t]+(.+?)[ \t]*$")
    for i, line in enumerate(lines):
        match = pattern.match(line)
        if match is None:
            continue
        text = _TRAILING_COLON_RE.sub("", match.group(1)).strip()
        # Drop trailing "(...)" clarifier for prefix-style matching.
        base = text.split("(", 1)[0].strip()
        found[base.casefold()] = i

    errors: list[str] = []
    for name in _CHECKLIST_SUBSECTIONS:
        if name.casefold() not in found:
            errors.append(
                f"::error::Checklist section is missing required H3 "
                f"subsection: ### {name} (post-2026-05-26 PR shape)."
            )

    # For each present subsection, ensure at least one item exists between
    # its H3 and the next H3 / EOF.
    h3_positions = sorted(found.items(), key=lambda kv: kv[1])
    for idx, (name_key, start) in enumerate(h3_positions):
        end = (
            h3_positions[idx + 1][1]
            if idx + 1 < len(h3_positions)
            else len(lines)
        )
        chunk = "\n".join(lines[start + 1 : end])
        if _CHECKLIST_ITEM_RE.search(chunk) is None:
            # Find the canonical name for the error message.
            canonical = next(
                (n for n in _CHECKLIST_SUBSECTIONS if n.casefold() == name_key),
                name_key,
            )
            errors.append(
                f"::error::Checklist subsection ### {canonical} has no "
                f"'- [ ]' or '- [x]' items (post-2026-05-26 PR shape)."
            )
    return errors


def verify_pr_agent_attribution_footer(
    body: str, *, harness_appends_footer: bool = False
) -> list[str]:
    """Return errors when the PR body lacks a trailing agent footer.

    The footer is agent-agnostic by design: ``Claude Code``, ``Codex``,
    or a future agent name all satisfy the label slot as long as the
    final non-empty line is ``_Generated by [<agent>](<url>)_``.

    More than one footer line is rejected (mirroring
    :func:`verify_codex_attribution_footer`): the web harness
    auto-appends a session footer, so a manually added footer plus the
    auto-append would otherwise yield a duplicate that this gate must
    catch. Refs #784.

    ``harness_appends_footer`` inverts the requirement for the Claude web
    harness ``create_pull_request`` path (Refs #1025). That harness
    auto-appends exactly one session footer to the stored body, so a
    footer the agent adds before the call becomes a duplicate that fails
    the server gate and forces a manual ``update_pull_request`` repair.
    When the flag is set the body must carry NO footer (the harness
    supplies the single one); any footer present is rejected so the
    no-duplicate guarantee is deterministic rather than repaired per PR.
    The server-side gate and the ``update_pull_request`` path (which the
    harness does not auto-append to) leave the flag False, so they keep
    requiring exactly one trailing footer. This mirrors the env-keyed
    Codex footer path so the two agent paths stay symmetric and auditable.
    """
    cleaned = strip_html_comments(body.replace("\r", "")).rstrip()
    lines = cleaned.splitlines()
    matching = [
        line for line in lines if _AGENT_ATTRIBUTION_FOOTER_RE.fullmatch(line)
    ]
    if harness_appends_footer:
        if matching:
            return [
                "::error::Under the Claude web harness (CLAUDE_CODE_REMOTE), "
                "create_pull_request auto-appends exactly one session footer. "
                "Do not add an agent-attribution footer to the create body -- "
                "the manual footer plus the auto-appended footer produces a "
                "duplicate. Remove the trailing footer line."
            ]
        return []
    if len(matching) > 1:
        return [
            "::error::PR body has multiple agent-attribution footers. "
            "Keep exactly one final footer line (a manual footer plus the "
            "harness auto-appended session footer produces a duplicate)."
        ]
    if lines and _AGENT_ATTRIBUTION_FOOTER_RE.fullmatch(lines[-1]):
        return []
    return [
        "::error::PR body is missing trailing agent-attribution footer. "
        "Add a final line like '_Generated by [Agent Name](https://...)_' "
        "(post-2026-05-26 PR shape)."
    ]


_ANGLE_TOKEN_RE = re.compile(r"<[^<>\n]+>")
_BLANK_RUN_RE = re.compile(r"\n{3,}")


def collapse_duplicate_footer(body: str) -> str:
    """Return *body* with a trailing run of agent-attribution footers collapsed.

    ``mcp__github__create_pull_request`` auto-appends a session footer even
    when the authored body already ends with one, producing two footer
    lines. This keeps the last footer (the harness-appended session footer
    is authoritative) and drops earlier agent-attribution footer lines, then
    collapses any blank-line run a removal left behind. A body with zero or
    one footer is returned unchanged (modulo ``\\r`` stripping). Refs #1361.
    """
    text = body.replace("\r", "")
    lines = text.split("\n")
    footer_idxs = [
        i for i, line in enumerate(lines)
        if _AGENT_ATTRIBUTION_FOOTER_RE.fullmatch(line.strip())
    ]
    if len(footer_idxs) <= 1:
        return text
    drop = set(footer_idxs[:-1])
    kept = [line for i, line in enumerate(lines) if i not in drop]
    return _BLANK_RUN_RE.sub("\n\n", "\n".join(kept))


def normalize_pr_body(body: str) -> str:
    """Return *body* with MCP write-tool corruption deterministically undone.

    ``mcp__github__create_pull_request`` / ``update_pull_request`` store the
    body with HTML-entity encoding applied (``&`` -> ``&amp;``, ``"`` ->
    ``&#34;``, ``>`` -> ``&gt;``, ``<`` -> ``&lt;``) and append a duplicate
    agent-attribution footer. This reverses the encoding via
    :func:`html.unescape` and collapses the duplicate footer via
    :func:`collapse_duplicate_footer`, so the normalized text matches the
    body the agent authored. The function is idempotent on an already-clean
    body. Refs #1361 (R1), #892.

    Angle-bracket *content* the tool dropped entirely (e.g. the
    ``<sha>`` token in ``git revert <sha>``) is unrecoverable from the
    stored body; use :func:`detect_dropped_angle_tokens` against the
    authored body to detect that separately.
    """
    return collapse_duplicate_footer(html.unescape(body))


def detect_dropped_angle_tokens(authored: str, stored: str) -> list[str]:
    """Return ``<...>`` tokens present in *authored* but absent from *stored*.

    The MCP write tools drop angle-bracket-delimited tokens entirely rather
    than HTML-encoding them, which is unrecoverable by
    :func:`normalize_pr_body`. Comparing the authored body (still intact in
    the PostToolUse ``tool_input``) against the stored body surfaces each
    dropped token so the agent can rephrase (e.g. wrap the token in
    backticks) instead of silently shipping a body with missing content.
    The stored side is HTML-unescaped first so a token that survived only as
    ``&lt;sha&gt;`` is not falsely reported as dropped. Refs #1361 (R1).
    """
    stored_norm = html.unescape(stored)
    seen: set[str] = set()
    dropped: list[str] = []
    for token in _ANGLE_TOKEN_RE.findall(authored):
        if token not in stored_norm and token not in seen:
            seen.add(token)
            dropped.append(token)
    return dropped


def detect_placeholder_tokens(body: str) -> list[str]:
    """Return ``::error::`` strings for unfilled angle-bracket placeholder tokens.

    Tokens like the unfilled verification placeholder the template ships with
    are flagged when they appear outside HTML comments. Tokens inside HTML
    comment blocks are exempt (they serve as documentation examples).
    """
    cleaned = strip_html_comments(body.replace("\r", ""))
    seen: set[str] = set()
    errors: list[str] = []
    for token in _ANGLE_TOKEN_RE.findall(cleaned):
        if token not in seen:
            seen.add(token)
            errors.append(
                f"::error::PR body contains unfilled placeholder token {token!r}. "
                "Replace the placeholder with the actual value before creating the PR."
            )
    return errors


def verify_section_substantive_content(body: str) -> list[str]:
    """Return ``::error::`` strings for required PR sections with no substantive content.

    A section is empty when its content (after HTML comment removal) contains
    only blank lines or bare dash bullets (``-``). At least one non-dash,
    non-blank line is required to pass.
    """
    required = required_sections("pull_request", body=body)
    errors: list[str] = []
    for section_name in required:
        content = extract_section_body(body, section_name)
        # extract_section_body already strips HTML comments
        non_empty = [
            line for line in content.splitlines()
            if line.strip() and not _BARE_DASH_RE.fullmatch(line.strip())
        ]
        if not non_empty:
            errors.append(
                f"::error::PR body section ## {section_name} has no substantive "
                "content (only blank lines or bare dash bullets). "
                "Fill in the section before creating the PR."
            )
    return errors


def build_codex_attribution_footer(model: str) -> str:
    """Return the canonical Codex GitHub provenance footer."""
    normalized = model.strip()
    if not normalized:
        raise ValueError("Codex model identifier must not be empty")
    if any(ord(ch) < 32 or ord(ch) > 126 for ch in normalized):
        raise ValueError("Codex model identifier must be printable ASCII")
    return f"{_CODEX_FOOTER_PREFIX}{normalized}._"


def verify_codex_attribution_footer(body: str, *, model: str) -> list[str]:
    """Return errors when a Codex GitHub post lacks its provenance footer."""
    try:
        expected = build_codex_attribution_footer(model)
    except ValueError as exc:
        return [f"::error::Codex attribution footer cannot be checked: {exc}."]

    cleaned = strip_html_comments(body.replace("\r", "")).rstrip()
    lines = [line for line in cleaned.splitlines() if line.strip()]
    matching = [line for line in lines if _CODEX_FOOTER_RE.fullmatch(line)]
    if len(matching) > 1:
        return [
            "::error::Codex GitHub body has multiple Codex attribution "
            "footers. Keep exactly one final footer line."
        ]
    if not lines or lines[-1] != expected:
        return [
            "::error::Codex GitHub body is missing trailing attribution "
            f"footer. Add this final line: {expected}"
        ]
    return []


def _parse_iso(value: str) -> datetime | None:
    if not value:
        return None
    text = value.strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=UTC)
    return parsed


def is_within_gate_window(created_at: str, cutoff: str) -> bool:
    """Return True when *created_at* is at or after *cutoff*.

    Empty or unparseable inputs default to True (enforce). A parseable
    *created_at* that strictly precedes a parseable *cutoff* returns
    False so the caller can short-circuit with a skip message.
    """
    created = _parse_iso(created_at)
    cut = _parse_iso(cutoff)
    if created is None or cut is None:
        return True
    return created >= cut


def _verify(
    kind: str,
    body: str,
    *,
    author: str | None = None,
    created_at: str = "",
    cutoff: str = "",
    shape_cutoff: str = "",
) -> int:
    if author is not None and author in _TRUSTED_BOT_LOGINS:
        print(f"skipped: trusted bot author ({author})")
        return 0

    if created_at and cutoff and not is_within_gate_window(created_at, cutoff):
        print(
            f"skipped: {kind} created at {created_at} predates gate cutoff "
            f"{cutoff}."
        )
        return 0

    required = required_sections(kind, body=body)
    headings = extract_headings(body)
    missing = missing_sections(required, headings)

    if missing:
        for name in missing:
            print(
                f"::error::{kind} body is missing required section: "
                f"## {name} (or ### {name})."
            )
        return 1

    # PR H2 allowlist: a PR body may carry only the headings in
    # _PR_ALLOWED. This runs only for in-window bodies (the created_at <
    # cutoff skip above already returned 0 for the back-catalog), so a
    # historical PR with an unlisted heading is not retro-failed. Refs #1396.
    if kind == "pull_request":
        allowlist_errors = verify_pr_allowed_sections(body)
        if allowlist_errors:
            for msg in allowlist_errors:
                print(msg)
            return 1

    # Shape gate: post-2026-05-26 PR template enforces Verification
    # command/result pairs and Checklist subsections. The gate is
    # opt-in: callers (workflow / CLI) must pass a non-empty shape_cutoff
    # to enable it, separating it from the baseline H2 cutoff so the two
    # can be rolled out independently. Within an enabled gate, bodies
    # whose created_at predates the cutoff are skipped (back-catalog
    # exempt). An empty created_at means "no timestamp known, enforce".
    if (
        kind == "pull_request"
        and shape_cutoff
        and (not created_at or is_within_gate_window(created_at, shape_cutoff))
    ):
        shape_errors = verify_pr_verification_pairs(
            body
        ) + verify_pr_checklist_subsections(
            body
        ) + verify_pr_agent_attribution_footer(
            body
        ) + detect_placeholder_tokens(
            body
        ) + verify_section_substantive_content(body)
        if shape_errors:
            for msg in shape_errors:
                print(msg)
            return 1

    print(f"OK: {kind} body contains all required sections.")
    return 0


def _resolve_body(args: argparse.Namespace) -> str:
    if args.body_file is not None:
        return Path(args.body_file).read_text(encoding="utf-8")
    env_name = "PR_BODY" if args.kind == "pull_request" else "ISSUE_BODY"
    return os.environ.get(env_name, "")


def _resolve_author(args: argparse.Namespace) -> str | None:
    if args.author is not None:
        return args.author or None
    env_name = "PR_AUTHOR" if args.kind == "pull_request" else "ISSUE_AUTHOR"
    return os.environ.get(env_name) or None


def _resolve_created_at(args: argparse.Namespace) -> str:
    if args.created_at is not None:
        return args.created_at
    env_name = (
        "PR_CREATED_AT" if args.kind == "pull_request" else "ISSUE_CREATED_AT"
    )
    return os.environ.get(env_name, "")


def _resolve_cutoff(args: argparse.Namespace) -> str:
    if args.cutoff is not None:
        return args.cutoff
    return os.environ.get("BODY_POLICY_CUTOFF", "")


def _resolve_shape_cutoff(args: argparse.Namespace) -> str:
    if args.shape_cutoff is not None:
        return args.shape_cutoff
    return os.environ.get("BODY_POLICY_SHAPE_CUTOFF", "")


def _cmd_verify(args: argparse.Namespace) -> int:
    body = _resolve_body(args)
    author = _resolve_author(args)
    created_at = _resolve_created_at(args)
    cutoff = _resolve_cutoff(args)
    shape_cutoff = _resolve_shape_cutoff(args)
    return _verify(
        args.kind,
        body,
        author=author,
        created_at=created_at,
        cutoff=cutoff,
        shape_cutoff=shape_cutoff,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_verify = sub.add_parser(
        "verify",
        help="Verify a body contains its template's required H2/H3 sections.",
    )
    p_verify.add_argument(
        "--kind",
        choices=("issue", "pull_request"),
        required=True,
        help="GitHub event object kind being validated.",
    )
    p_verify.add_argument(
        "--body-file",
        help=(
            "Path to a file containing the body. Falls back to ISSUE_BODY or "
            "PR_BODY (per --kind) when omitted."
        ),
    )
    p_verify.add_argument(
        "--author",
        help=(
            "Author login. When the login is in the trusted-bot allowlist the "
            "check is skipped. Falls back to ISSUE_AUTHOR or PR_AUTHOR when "
            "omitted."
        ),
    )
    p_verify.add_argument(
        "--created-at",
        help=(
            "ISO-8601 creation timestamp of the issue/PR. Compared against "
            "--cutoff to keep the back-catalog exempt. Falls back to "
            "ISSUE_CREATED_AT or PR_CREATED_AT when omitted."
        ),
    )
    p_verify.add_argument(
        "--cutoff",
        help=(
            "ISO-8601 cutoff. Bodies created strictly before this moment are "
            "skipped. Falls back to BODY_POLICY_CUTOFF when omitted."
        ),
    )
    p_verify.add_argument(
        "--shape-cutoff",
        help=(
            "ISO-8601 cutoff for the post-2026-05-26 PR shape gate "
            "(Verification command/result pairs and Checklist H3 "
            "subsections). PRs created strictly before this moment skip the "
            "shape gate while still being subject to the baseline H2 gate. "
            "Falls back to BODY_POLICY_SHAPE_CUTOFF when omitted."
        ),
    )
    p_verify.set_defaults(func=_cmd_verify)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
