#!/usr/bin/env python3
"""PreToolUse gate: deny a Bash ``git push`` that would publish an unsigned commit.

Refs #1959. The agent-Bash-tool sibling of ``preflight_signed_commits.py`` (the
pre-push preflight step) and the second, independent layer of defense in depth
(CLAUDE.md section 4) over the macOS / codex-desktop broken-signing scenario
(PRs #1744 / #1766 / #1767): where the preflight step guards the local git
push, this gate guards the push an agent issues through the Bash tool, before
it leaves the working tree. Both layers share ``_commit_signatures`` so the
"is this commit signed" rule has one definition.

Registered as a ``PreToolUse`` ``Bash`` hook in ``.claude/settings.json`` and
mirrored into ``.codex/hooks.json`` / ``.devin/hooks.v1.json`` via
``scripts/agent_hooks_source.json`` (regenerated by ``gen_agent_hooks.py``).
``scan_hook_coverage_drift.py`` then enforces three-way cross-agent parity, so
the gate cannot be silently dropped from one agent; that drift gate is the
"cannot silently regress" guarantee the gate's coverage relies on.

Range under inspection
----------------------
The local refs the push command actually names, parsed from its refspec (not a
hard-coded HEAD): ``git push origin feature`` inspects ``feature``,
``git push origin HEAD:main`` inspects ``HEAD``, ``git push --all`` inspects
every local branch head, and a bare ``git push`` inspects the current branch
(HEAD). For each ref the range is ``<base>..<ref>`` where ``base`` is that ref's
own ``origin/<ref>`` remote-tracking branch when it resolves, else
``origin/main``. Signed-ness is the ``gpgsig``-header presence check from
``_commit_signatures`` (format-agnostic, no verification infra). A deliberately
unsigned push can carry the ``unsigned-ack`` marker in the command, mirroring
``gate_unsigned_commit_bash``.

Failure policy
--------------
Fail-open everywhere except a matched unsigned commit (CLAUDE.md section 4): a
non-Bash event, a non-push command, a delete-only push, an unresolved base, or
any git error yields no decision so the push proceeds and the preflight step
plus the server-side ``required_signatures`` ruleset remain as backstops. A
push carrying a confirmed unsigned, non-acked commit is always denied.

Contract:
- Inputs: a PreToolUse hook event as JSON on stdin (``tool_name`` plus
  ``tool_input`` with a ``command`` string). No flags.
- Outputs: a JSON ``permissionDecision`` deny object on stdout when the push
  would publish an unsigned commit; nothing on stdout on pass-through. Always
  exits 0.

Tested by ``tests/test_gate_unsigned_commit_push.py``. Refs #1959.
"""

from __future__ import annotations

import re
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from _commit_signatures import ACK_MARKER, CommitSignature, list_signatures, select_unsigned
from _git import run_git
from _hook_runtime import build_deny, run_tool_hook

REPO_ROOT = Path(__file__).resolve().parent.parent

# Optional ``rtk`` prefix: the rtk auto-rewrite hook rewrites ``git push`` ->
# ``rtk git push`` (Refs #1199), so match both. Mirrors the sibling push gates.
_GIT_PUSH_RE = re.compile(r"(?m)^\s*(?:rtk\s+)?git\s+push\b")

# Local ref to inspect when the push names no explicit refspec: git's
# ``push.default`` publishes the current branch, which HEAD resolves to.
_HEAD = "HEAD"
_FALLBACK_BASE = "origin/main"

# git push flags that consume one following token as their value, so the token
# after them is NOT a positional (remote / refspec). Mirrors the value-flag set
# in preflight_push_session_branch.py.
_FLAGS_WITH_VALUE: frozenset[str] = frozenset({
    "-o", "--push-option", "--receive-pack", "--exec", "--repo",
    "--recurse-submodules", "--signed",
})
# Flags that mean "this push deletes a remote ref"; no local content is
# published, so there is nothing to inspect.
_DELETE_FLAGS: frozenset[str] = frozenset({"-d", "--delete"})
# Flags that publish every local branch; the inspected set is all branch heads.
_ALL_BRANCH_FLAGS: frozenset[str] = frozenset({"--all", "--mirror"})


@dataclass(frozen=True)
class PushPlan:
    """Which local refs a ``git push`` command publishes.

    ``all_branches`` means ``--all`` / ``--mirror`` (inspect every local branch
    head). Otherwise ``refs`` is the explicit local source refs; an empty
    ``refs`` with ``all_branches`` False means a delete-only push with no
    content to inspect.
    """

    all_branches: bool
    refs: tuple[str, ...]


def parse_push_sources(command: str) -> PushPlan:
    """Parse the local refs a ``git push`` *command* would publish.

    Pure function (no I/O) so the refspec parsing is unit-testable. Resolves the
    Codex review point: a hard-coded ``HEAD`` range inspects the current branch,
    not the ref the command actually names, so ``git push origin feature`` run
    from another branch would miss an unsigned commit on ``feature``. The local
    source of each refspec is the part before ``:`` (``src`` in ``src:dst``,
    ``HEAD`` in ``HEAD:dst``); a bare ``git push`` inspects HEAD.
    """
    match = re.search(r"git\s+push\b([^&;|\n]*)", command)
    if not match:
        return PushPlan(all_branches=False, refs=(_HEAD,))
    try:
        tokens = shlex.split(match.group(1))
    except ValueError:
        return PushPlan(all_branches=False, refs=(_HEAD,))

    positionals: list[str] = []
    index = 0
    while index < len(tokens):
        token = tokens[index]
        if token in _ALL_BRANCH_FLAGS:
            return PushPlan(all_branches=True, refs=())
        if token in _DELETE_FLAGS:
            return PushPlan(all_branches=False, refs=())
        if token in _FLAGS_WITH_VALUE:
            index += 2  # skip the flag and its value token
            continue
        if token.startswith("-"):
            index += 1  # any other flag consumes no positional
            continue
        positionals.append(token)
        index += 1

    # The first positional is the remote; the rest are refspecs. With no
    # refspec, git publishes the current branch (HEAD). With refspecs present,
    # inspect exactly their local sources; if every one is a delete
    # (``:dst``), the result is empty (nothing to inspect), NOT a HEAD fallback.
    refspecs = positionals[1:]
    if not refspecs:
        return PushPlan(all_branches=False, refs=(_HEAD,))

    sources: list[str] = []
    for spec in refspecs:
        source = spec.lstrip("+").split(":", 1)[0]
        if source:  # empty source (``:dst``) is a delete refspec; no content
            sources.append(source)
    return PushPlan(all_branches=False, refs=tuple(sources))


def _all_branch_heads(repo: Path) -> list[str]:
    """Return every local branch head name under *repo* (for ``--all`` pushes)."""
    completed = run_git(["for-each-ref", "--format=%(refname:short)", "refs/heads/"], cwd=repo)
    if completed.returncode != 0:
        return []
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def _resolve_push_base(repo: Path, ref: str) -> str | None:
    """Return the base ``ref`` diffs against, or None when none resolves.

    Prefers the ref's own remote-tracking branch (the commits not yet on the
    remote); when that does not exist (a new branch, or HEAD), falls back to
    ``origin/main``. ``HEAD`` has no ``origin/HEAD`` content counterpart, so it
    resolves straight to the fallback.
    """
    candidates = (_FALLBACK_BASE,) if ref == _HEAD else (f"origin/{ref}", _FALLBACK_BASE)
    for base in candidates:
        completed = run_git(["rev-parse", "--verify", "--quiet", f"{base}^{{commit}}"], cwd=repo)
        if completed.returncode == 0 and completed.stdout.strip():
            return base
    return None


def _unsigned_in_push(repo: Path, command: str) -> list[CommitSignature]:
    """Return the unsigned, non-acked commits *command*'s push would publish.

    Inspects the actual local refs the push names (not a hard-coded HEAD), so a
    push of another branch is checked against that branch. Fail-open: returns
    ``[]`` on an unresolved base or any git error so the gate never blocks on an
    inconclusive read; the preflight step and the server ruleset remain
    backstops.
    """
    try:
        plan = parse_push_sources(command)
        refs = _all_branch_heads(repo) if plan.all_branches else list(plan.refs)
        seen: set[str] = set()
        unsigned: list[CommitSignature] = []
        for ref in refs:
            base = _resolve_push_base(repo, ref)
            if base is None:
                continue
            for record in select_unsigned(list_signatures(repo, [f"{base}..{ref}"])):
                if record.sha not in seen:
                    seen.add(record.sha)
                    unsigned.append(record)
    except (RuntimeError, OSError):
        return []
    return unsigned


def decide(tool_name: str, tool_input: dict[str, Any]) -> dict[str, Any] | None:
    """Return a deny decision for a push that would publish an unsigned commit."""
    if tool_name != "Bash":
        return None
    command = str(tool_input.get("command") or "")
    if not _GIT_PUSH_RE.search(command):
        return None
    if ACK_MARKER in command:
        return None

    unsigned = _unsigned_in_push(REPO_ROOT, command)
    if not unsigned:
        return None

    listed = "\n".join(f"  {c.sha[:12]} {c.subject}" for c in unsigned)
    return build_deny(
        "Blocked by scripts/gate_unsigned_commit_push.py: this push would publish "
        f"{len(unsigned)} unsigned commit(s):\n{listed}\n\n"
        "This repository requires signed commits (the main-protection ruleset "
        "enforces required_signatures), so an unsigned commit blocks the merge. "
        "Fix your signing setup (git config commit.gpgsign should be true and "
        "user.signingkey / gpg.format must resolve a working key), then re-sign "
        "the range:\n"
        "  git rebase --exec 'git commit --amend --no-edit -S' origin/main\n\n"
        "If an unsigned commit is genuinely intended and reviewed, add an "
        f"'{ACK_MARKER}' line to its message, or append '{ACK_MARKER}' to this "
        "command to opt in."
    )


def main(argv: list[str] | None = None) -> int:
    del argv
    return run_tool_hook("gate_unsigned_commit_push", decide, auditable=False)


if __name__ == "__main__":
    raise SystemExit(main())
