#!/usr/bin/env python3
"""PreToolUse gate: forbid direct edits to APM-managed skill directories.

``.agents/skills/`` and ``.claude/skills/`` are the two committed copies of the
upstream APM dependency (``obra/superpowers``, pinned in ``apm.yml`` /
``apm.lock.yaml``). They are *generated*: ``apm compile`` expands the pinned
dependency into both trees, so the source of truth is the pin, not the files on
disk. An agent that edits a file under either prefix with ``Edit``/``Write``
(or writes to it from ``Bash``) makes a change that the next ``apm compile``
silently overwrites; the edit is lost with no error. Retro #1892 traced exactly
this to PR #1891, where a bulk em-dash replacement touched 20 files under
``.agents/skills/`` before human review caught it. ``scan_repo_em_dash.py`` and
``scan_repo_double_hyphen.py`` already exclude these prefixes in their
``_SKIP_PREFIXES``, documenting the constraint at the script level; this gate
enforces it at tool-call time, the earliest point an edit can be stopped.

This is the same class of gate as ``gate_generated_scripts_manual_edit.py`` (a
single-producer surface protected from hand edits), shifted left from CI to the
PreToolUse boundary so the wasted edit never lands.

Covered tools:

- ``Edit`` / ``Write`` / ``MultiEdit`` / ``NotebookEdit``: the ``file_path``
  (or ``notebook_path``) is checked against the managed prefixes; a match is
  denied before the file is touched.
- ``Bash``: a command that *writes* to a managed path is denied. Detection is
  high-confidence / low-false-positive; a shell redirection (``>`` / ``>>``)
  whose target is a managed path, or a mutating command (``cp``, ``mv``,
  ``rm``, ``tee``, ``sed``, ``install``, ``ln``, ``touch``, ``mkdir``,
  ``rmdir``, ``dd``, ``truncate``, ``chmod``, ``chown``, ``rsync``, ``shred``)
  carrying a managed path as an argument. A read (``cat``, ``grep``, ``ls`` on
  a managed path) is never blocked.

Design (CLAUDE.md section 4: make wrong actions hard, right actions easy):

- The gate denies rather than silently allowing; the deny reason names the
  blocked path and the only correct change path: update the ``obra/superpowers``
  pin in ``apm.yml`` / ``apm.lock.yaml`` and run ``apm compile`` to regenerate
  both trees.
- Bash detection is command-position aware (each shell segment is tokenized and
  only its leading command is classified) so a managed path mentioned inside an
  argument or a quoted string of a non-mutating command does not trip the gate.
- Fail-open is narrow and intentional: a malformed stdin event logs to stderr
  and exits 0 (per CLAUDE.md section 4, a hook bug never wedges the session).
  A matched edit/write is always denied.

Contract:
- Inputs: a PreToolUse hook event as JSON on stdin (``tool_name`` plus
  ``tool_input``; ``file_path``/``notebook_path`` for the edit tools, a
  ``command`` string for Bash). No flags.
- Outputs: a JSON PreToolUse deny payload on stdout when the call targets a
  managed path; nothing on stdout on pass-through. Always exits 0.
- Failure policy: fails open at the stdin boundary and fails loud-by-deny on a
  matched managed-path write.

Tested by ``tests/test_gate_agents_skills_edit.py``. Refs #2066, #1892, #1891.
"""

from __future__ import annotations

import re
import shlex
from pathlib import PurePosixPath
from typing import Any

from _hook_runtime import build_deny, run_tool_hook

# APM-managed path prefixes. Byte-for-byte the same set
# ``scan_repo_em_dash.py`` / ``scan_repo_double_hyphen.py`` skip in their
# ``_SKIP_PREFIXES``: the two committed copies of the upstream ``obra/superpowers``
# APM dependency, regenerated by ``apm compile``. Trailing slashes are
# deliberate so a sibling like ``.agents/skillset/`` never matches.
MANAGED_PREFIXES: tuple[str, ...] = (".agents/skills/", ".claude/skills/")

# Tools that modify working-tree files. NotebookEdit carries its target in
# ``notebook_path`` rather than ``file_path``; both are handled.
_EDIT_TOOLS: frozenset[str] = frozenset({"Edit", "Write", "MultiEdit", "NotebookEdit"})

# Mutating Bash commands whose path arguments are write targets. A read-only
# command (cat/grep/ls/head/...) is intentionally absent: reading a managed
# path is allowed; only writes are blocked.
_WRITE_COMMANDS: frozenset[str] = frozenset(
    {
        "cp",
        "mv",
        "rm",
        "tee",
        "sed",
        "install",
        "ln",
        "touch",
        "mkdir",
        "rmdir",
        "dd",
        "truncate",
        "chmod",
        "chown",
        "rsync",
        "shred",
    }
)

# Shell separators that begin a new command position.
_SEGMENT_SPLIT = re.compile(r"&&|\|\||[;|\n]")

# A leading ``NAME=value`` environment assignment to skip before the command.
_ASSIGN_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")

# A redirection operator and its target token, e.g. ``> .agents/skills/x``,
# ``>>foo``, ``2>/dev/null``. The target is the first non-space run after the
# operator; a leading file-descriptor digit and ``&`` (as in ``2>&1``) are not
# captured as paths because ``&1`` normalizes to a non-managed token.
_REDIRECT_RE = re.compile(r">>?\s*([^\s|&;<>]+)")


def _normalize(path: str) -> str:
    """Strip quotes/whitespace and leading ``./`` segments from a raw token."""
    token = path.strip().strip("'\"")
    while token.startswith("./"):
        token = token[2:]
    return token


def matched_prefix(path: str) -> str | None:
    """Return the managed prefix *path* falls under, or None.

    Pure string logic so the gate is unit-testable without a live repository.
    Matches a repo-relative path (``.agents/skills/x``, ``./.agents/skills/x``)
    and an absolute path that contains the managed segment
    (``/home/user/repo/.agents/skills/x``). A bare ``/`` before the prefix is
    required, so ``/repo.agents/skills/x`` (no slash before ``.agents``) does
    not match.
    """
    token = _normalize(path)
    for prefix in MANAGED_PREFIXES:
        if token.startswith(prefix) or ("/" + prefix) in token:
            return prefix
    return None


def _tokenize(segment: str) -> list[str]:
    """Best-effort shell tokenization; fall back to whitespace split."""
    try:
        return shlex.split(segment)
    except ValueError:
        return segment.split()


def _leading_command(tokens: list[str]) -> tuple[str, list[str]]:
    """Return ``(command_basename, args)``, skipping ``VAR=value`` prefixes.

    The basename is used so ``/bin/cp`` classifies the same as ``cp``.
    """
    index = 0
    while index < len(tokens) and _ASSIGN_RE.match(tokens[index]):
        index += 1
    if index >= len(tokens):
        return "", []
    name = PurePosixPath(_normalize(tokens[index])).name
    return name, tokens[index + 1 :]


def _segment_write_targets(segment: str) -> list[str]:
    """Return managed paths *segment* would write to (redirects + mutators)."""
    targets: list[str] = []
    # Redirection targets, regardless of the leading command (``echo x > path``).
    for raw_target in _REDIRECT_RE.findall(segment):
        prefix = matched_prefix(raw_target)
        if prefix is not None:
            targets.append(_normalize(raw_target))
    # A mutating command carrying a managed path as any argument.
    cmd, args = _leading_command(_tokenize(segment))
    if cmd in _WRITE_COMMANDS:
        for arg in args:
            if matched_prefix(arg) is not None:
                targets.append(_normalize(arg))
    return targets


def managed_write_targets(command: str) -> list[str]:
    """Return the managed paths *command* would write to, across shell segments.

    Empty when the command writes to no managed path (the pass-through case).
    Deduplicated while preserving first-seen order so the deny reason is stable.
    """
    seen: dict[str, None] = {}
    for segment in (seg.strip() for seg in _SEGMENT_SPLIT.split(command) if seg.strip()):
        for target in _segment_write_targets(segment):
            seen.setdefault(target, None)
    return list(seen)


def _change_path_guidance() -> str:
    """Return the shared 'how to change these files correctly' instruction."""
    return (
        "These files are generated: `apm compile` expands the upstream "
        "`obra/superpowers` dependency (pinned in apm.yml / apm.lock.yaml) into "
        "both `.agents/skills/` and `.claude/skills/`, so a direct edit is "
        "silently overwritten on the next compile (retro #1892, PR #1891).\n\n"
        "To change skill content, do NOT edit these paths. Instead: update the "
        "`obra/superpowers` pin in apm.yml / apm.lock.yaml (open an issue first "
        "per CLAUDE.md section 3), run `apm compile` to regenerate both trees, "
        "and commit the regenerated output.\n\n"
        "See docs/standards/apm-managed-paths.md. Refs #2066, #1892, #1891."
    )


def _deny_edit(path: str, prefix: str) -> dict[str, Any]:
    return build_deny(
        f"Blocked by scripts/gate_agents_skills_edit.py: '{path}' is under the "
        f"APM-managed prefix '{prefix}', which must not be edited directly.\n\n"
        + _change_path_guidance()
    )


def _deny_bash(targets: list[str]) -> dict[str, Any]:
    pretty = ", ".join(targets)
    return build_deny(
        f"Blocked by scripts/gate_agents_skills_edit.py: this Bash command writes "
        f"to APM-managed path(s) ({pretty}), which must not be edited directly.\n\n"
        + _change_path_guidance()
    )


def _decide_edit(tool_input: dict[str, Any]) -> dict[str, Any] | None:
    raw_path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(raw_path, str) or not raw_path:
        return None  # no target path; fail open
    prefix = matched_prefix(raw_path)
    if prefix is None:
        return None
    return _deny_edit(raw_path, prefix)


def _decide_bash(command: str) -> dict[str, Any] | None:
    if not command.strip():
        return None
    targets = managed_write_targets(command)
    if not targets:
        return None
    return _deny_bash(targets)


def decide(tool_name: str, tool_input: dict[str, Any]) -> dict[str, Any] | None:
    """Return a deny decision when the call targets a managed path, else None."""
    if tool_name in _EDIT_TOOLS:
        return _decide_edit(tool_input)
    if tool_name == "Bash":
        return _decide_bash(str(tool_input.get("command") or ""))
    return None


def main(argv: list[str] | None = None) -> int:
    """Read PreToolUse JSON from stdin, write a deny decision when warranted."""
    del argv
    # auditable=False: a governance boundary protecting a single-producer
    # surface, in the same class as gate_irreversible_bash and
    # preflight_session_branch_authz; CLAUDE_GATE_MODE=audit must not disable it.
    return run_tool_hook("gate_agents_skills_edit", decide, auditable=False)


if __name__ == "__main__":
    raise SystemExit(main())
