#!/usr/bin/env python3
"""PreToolUse gate: deny a Bash ``git push`` that would publish an unsigned commit.

Refs #1959. The agent-Bash-tool sibling of ``preflight_signed_commits.py`` (the
pre-push preflight step) and the second, independent layer of defense in depth
(CLAUDE.md section 4) over the macOS / codex-desktop broken-signing scenario
(PRs #1744 / #1766 / #1767): where the preflight step guards the local git
push, this gate guards the push an agent issues through the Bash tool, before
it leaves the working tree. Both layers share ``_commit_signatures`` so the
"is this commit signed" rule has one definition.

Registered as a ``PreToolUse`` ``Bash`` hook in ``.claude/settings.json`` and
mirrored into ``.codex/hooks.json`` / ``.devin/hooks.v1.json`` via
``scripts/agent_hooks_source.json`` (regenerated by ``gen_agent_hooks.py``).
``scan_hook_coverage_drift.py`` then enforces three-way cross-agent parity, so
the gate cannot be silently dropped from one agent; that drift gate is the
"cannot silently regress" guarantee the gate's coverage relies on.

Range under inspection
----------------------
The commits the push would publish: ``<base>..HEAD`` where ``base`` is the
remote-tracking ref ``origin/<current-branch>`` when it resolves, else
``origin/main``. Only ``%G?`` code ``N`` (no signature present) is unsigned;
``E`` / ``U`` (signed but unverifiable locally) are NOT flagged. A deliberately
unsigned push can carry the ``unsigned-ack`` marker in the command, mirroring
``gate_unsigned_commit_bash``.

Failure policy
--------------
Fail-open everywhere except a matched unsigned commit (CLAUDE.md section 4): a
non-Bash event, a non-push command, a detached HEAD, an unresolved base, or any
git error yields no decision so the push proceeds and the preflight step plus
the server-side ``required_signatures`` ruleset remain as backstops. A push
carrying a confirmed unsigned, non-acked commit is always denied.

Contract:
- Inputs: a PreToolUse hook event as JSON on stdin (``tool_name`` plus
  ``tool_input`` with a ``command`` string). No flags.
- Outputs: a JSON ``permissionDecision`` deny object on stdout when the push
  would publish an unsigned commit; nothing on stdout on pass-through. Always
  exits 0.

Tested by ``tests/test_gate_unsigned_commit_push.py``. Refs #1959.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from _commit_signatures import ACK_MARKER, CommitSignature, list_signatures, select_unsigned
from _git import run_git
from _hook_runtime import build_deny, run_tool_hook

REPO_ROOT = Path(__file__).resolve().parent.parent

# Optional ``rtk`` prefix: the rtk auto-rewrite hook rewrites ``git push`` ->
# ``rtk git push`` (Refs #1199), so match both. Mirrors the sibling push gates.
_GIT_PUSH_RE = re.compile(r"(?m)^\s*(?:rtk\s+)?git\s+push\b")

_FALLBACK_BASE = "origin/main"


def _current_branch(repo: Path) -> str | None:
    """Return the checked-out branch name, or None on detached HEAD / error."""
    completed = run_git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=repo)
    if completed.returncode != 0:
        return None
    branch = completed.stdout.strip()
    if not branch or branch == "HEAD":  # empty or detached
        return None
    return branch


def _resolve_push_base(repo: Path, branch: str) -> str | None:
    """Return the ref the push range diffs against, or None when none resolves.

    Prefers ``origin/<branch>`` (the commits not yet on the remote branch); when
    the branch is new on the remote, falls back to ``origin/main``.
    """
    for ref in (f"origin/{branch}", _FALLBACK_BASE):
        completed = run_git(["rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"], cwd=repo)
        if completed.returncode == 0 and completed.stdout.strip():
            return ref
    return None


def _unsigned_in_push(repo: Path) -> list[CommitSignature]:
    """Return the unsigned, non-acked commits the current push would publish.

    Fail-open: returns ``[]`` on a detached HEAD, an unresolved base, or any git
    error so the gate never blocks on an inconclusive read.
    """
    try:
        branch = _current_branch(repo)
        if branch is None:
            return []
        base = _resolve_push_base(repo, branch)
        if base is None:
            return []
        records = list_signatures(repo, [f"{base}..HEAD"])
    except (RuntimeError, OSError):
        return []
    return select_unsigned(records)


def decide(tool_name: str, tool_input: dict[str, Any]) -> dict[str, Any] | None:
    """Return a deny decision for a push that would publish an unsigned commit."""
    if tool_name != "Bash":
        return None
    command = str(tool_input.get("command") or "")
    if not _GIT_PUSH_RE.search(command):
        return None
    if ACK_MARKER in command:
        return None

    unsigned = _unsigned_in_push(REPO_ROOT)
    if not unsigned:
        return None

    listed = "\n".join(f"  {c.sha[:12]} {c.subject}" for c in unsigned)
    return build_deny(
        "Blocked by scripts/gate_unsigned_commit_push.py: this push would publish "
        f"{len(unsigned)} unsigned commit(s):\n{listed}\n\n"
        "This repository requires signed commits (the main-protection ruleset "
        "enforces required_signatures), so an unsigned commit blocks the merge. "
        "Fix your signing setup (git config commit.gpgsign should be true and "
        "user.signingkey / gpg.format must resolve a working key), then re-sign "
        "the range:\n"
        "  git rebase --exec 'git commit --amend --no-edit -S' origin/main\n\n"
        "If an unsigned commit is genuinely intended and reviewed, add an "
        f"'{ACK_MARKER}' line to its message, or append '{ACK_MARKER}' to this "
        "command to opt in."
    )


def main(argv: list[str] | None = None) -> int:
    del argv
    return run_tool_hook("gate_unsigned_commit_push", decide, auditable=False)


if __name__ == "__main__":
    raise SystemExit(main())
