#!/usr/bin/env python3
"""Template-fill helper: emit a valid PR body skeleton from PULL_REQUEST_TEMPLATE.md.

Reads ``.github/PULL_REQUEST_TEMPLATE.md`` (or a domain-specific template when
``--kind`` is given), fills in the issue number, a placeholder verification
entry that satisfies the post-2026-05-26 command/result pair shape gate, and
the agent attribution footer. The output passes ``scripts/body_policy.py verify
--kind pull_request --shape-cutoff 2026-05-26T00:00:00Z --body-file <path>``
so agents can start from a policy-conformant skeleton instead of hand-rolling
the shape.

Usage::

    python3 scripts/pr_body_builder.py build --issue 938
    python3 scripts/pr_body_builder.py build --issue 938 --kind feat
    python3 scripts/pr_body_builder.py build --issue 938 \\
        --agent "Claude Code" --session-url "https://claude.ai/code/session_XYZ"
    python3 scripts/pr_body_builder.py build --issue 938 \\
        --agent Codex --model gpt-4o
    # Web-harness create path: omit the footer the harness auto-appends.
    python3 scripts/pr_body_builder.py build --issue 938 --no-footer
    python3 scripts/pr_body_builder.py list-kinds

Refs #938, #1825.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from body_policy import build_codex_attribution_footer

REPO_ROOT = Path(__file__).resolve().parent.parent
_TEMPLATE_PATH = REPO_ROOT / ".github" / "PULL_REQUEST_TEMPLATE.md"
_DOMAIN_TEMPLATE_DIR = REPO_ROOT / ".github" / "pr-body-templates"

_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
# Match bare "Closes #" (universal template) or "Closes #<digits>" (domain
# templates that embed a concrete example issue number). Both forms are
# replaced with "Closes #{issue}" at build time.
_CLOSES_PLACEHOLDER_RE = re.compile(r"^Closes #\d*\s*$", re.MULTILINE)
_EMPTY_VERIFICATION_RE = re.compile(
    r"^(-[ \t]+command:[ \t]*``[ \t]*\n[ \t]{2}result:[ \t]*``[ \t]*)$",
    re.MULTILINE,
)
_FOOTER_PLACEHOLDER_RE = re.compile(
    r"_Generated by \[Agent Name\]\(agent-session-url\)_"
    r"|_Generated by \[Claude Code\]\(https://claude\.ai/code/session_example\)_"
)

_WORKFLOW_ONLY_TOKENS: tuple[str, ...] = ("__GITHUB_SHA__", "__ISSUE_ANCHOR:")

_DEFAULT_AGENT = "Claude Code"
_DEFAULT_SESSION_URL = "https://claude.ai/code"
_VERIFICATION_PLACEHOLDER = (
    "- command: `COMMAND`\n  result: `RESULT`"
)


def _build_footer(agent: str, session_url: str, model: str | None) -> str:
    """Return the attribution footer line for the given agent."""
    if agent.strip().lower() == "codex":
        if not model:
            raise ValueError(
                "Codex attribution requires --model; "
                "e.g. --model gpt-4o"
            )
        return build_codex_attribution_footer(model)
    return f"_Generated by [{agent}]({session_url})_"


def _is_builder_compatible(template_path: Path) -> bool:
    """Return True if the template has no workflow-only token sequences."""
    text = template_path.read_text(encoding="utf-8")
    return not any(token in text for token in _WORKFLOW_ONLY_TOKENS)


def list_kinds() -> list[str]:
    """Return sorted list of builder-compatible domain template kind names."""
    return sorted(
        p.stem
        for p in _DOMAIN_TEMPLATE_DIR.glob("*.md")
        if _is_builder_compatible(p)
    )


def build(
    issue: int,
    *,
    agent: str = _DEFAULT_AGENT,
    session_url: str = _DEFAULT_SESSION_URL,
    model: str | None = None,
    kind: str | None = None,
    include_footer: bool = True,
    template_path: Path = _TEMPLATE_PATH,
) -> str:
    """Return a PR body skeleton with *issue*, agent footer, and verification placeholder filled in.

    When *kind* is given and a matching template exists in
    ``.github/pr-body-templates/<kind>.md``, that domain template is used as
    the base instead of the universal template. Falls back to *template_path*
    when no domain template is found. Run ``list-kinds`` to see available kinds.

    Footer asymmetry (Refs #1999 row 3, #1427): ``mcp__github__create_pull_request``
    under the remote web harness (``CLAUDE_CODE_REMOTE=true``) auto-appends the
    session footer, so the body passed to *create* must carry NONE; the later
    ``mcp__github__update_pull_request`` is not auto-appended and its gate
    requires exactly one footer. This builder appends a footer by default,
    which suits the local CLI and the update path. For the web-harness create
    path, pass ``include_footer=False`` (CLI ``--no-footer``) to emit a
    footerless body; the harness then supplies the single footer.

    The returned string passes ``body_policy.verify`` with the post-2026-05-26
    shape gate enabled once the placeholder sections (Summary, Facts,
    Assumptions, Risk, Rollback, Verification command/result) are replaced with
    real content.
    """
    if kind is not None:
        kind_path = _DOMAIN_TEMPLATE_DIR / f"{kind}.md"
        if kind_path.exists() and _is_builder_compatible(kind_path):
            template_path = kind_path

    raw = template_path.read_text(encoding="utf-8")

    # Strip HTML comments; they are for human template readers, not for
    # the body policy parser, and keeping them clutters the generated body.
    body = _HTML_COMMENT_RE.sub("", raw)

    # Collapse sequences of more than two blank lines that HTML comment
    # removal often leaves behind.
    body = re.sub(r"\n{3,}", "\n\n", body)

    # Fill in the issue number.
    body = _CLOSES_PLACEHOLDER_RE.sub(f"Closes #{issue}", body)

    # Replace bare dash bullets left by the template (content placeholders)
    # with "TBD" so the skeleton passes verify_section_substantive_content.
    body = re.sub(r"^-\s*$", "- TBD", body, flags=re.MULTILINE)

    # Replace the template's empty command/result placeholders with
    # non-empty ones that satisfy the shape gate regex.
    body = _EMPTY_VERIFICATION_RE.sub(_VERIFICATION_PLACEHOLDER, body)

    # Replace the attribution footer placeholder. On the web-harness create
    # path (include_footer=False) the placeholder is dropped entirely so the
    # harness-appended footer is the only one; the Codex --model requirement is
    # also moot there since no footer is built. Refs #1999 row 3, #1427.
    if include_footer:
        footer = _build_footer(agent, session_url, model)
        body = _FOOTER_PLACEHOLDER_RE.sub(footer, body)
    else:
        body = _FOOTER_PLACEHOLDER_RE.sub("", body)

    # Ensure the body ends with a single newline.
    return body.rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_build = sub.add_parser(
        "build",
        help=(
            "Emit a valid PR body skeleton for the given issue. "
            "Fill in the placeholder sections before creating the PR."
        ),
    )
    p_build.add_argument(
        "--issue",
        type=int,
        required=True,
        help="Issue number to reference (Closes #<number>).",
    )
    p_build.add_argument(
        "--kind",
        default=None,
        help=(
            "Change-type domain template to use (e.g. feat, fix, refactor). "
            "Run 'list-kinds' to see all available templates. "
            "Falls back to the universal template when no matching template exists."
        ),
    )
    p_build.add_argument(
        "--agent",
        default=_DEFAULT_AGENT,
        help=(
            f"Agent name for the attribution footer (default: {_DEFAULT_AGENT!r}). "
            "Use 'Codex' together with --model for the Codex-specific footer."
        ),
    )
    p_build.add_argument(
        "--session-url",
        default=_DEFAULT_SESSION_URL,
        help=(
            f"Session URL for the attribution footer "
            f"(default: {_DEFAULT_SESSION_URL!r}). "
            "Not used when --agent Codex is given."
        ),
    )
    p_build.add_argument(
        "--model",
        default=None,
        help="Codex model identifier (required when --agent Codex).",
    )
    p_build.add_argument(
        "--no-footer",
        dest="include_footer",
        action="store_false",
        help=(
            "Omit the attribution footer. Use ONLY for the remote web-harness "
            "create_pull_request path (CLAUDE_CODE_REMOTE=true), where the "
            "harness auto-appends the session footer; the body it stores must "
            "carry none. The default keeps a footer (local CLI / "
            "update_pull_request path, whose gate requires one)."
        ),
    )
    p_build.add_argument(
        "--template",
        default=str(_TEMPLATE_PATH),
        help="Path to the PR body template (default: .github/PULL_REQUEST_TEMPLATE.md).",
    )

    sub.add_parser(
        "list-kinds",
        help=(
            "List available domain template kinds from "
            ".github/pr-body-templates/. Pass a kind name to 'build --kind'."
        ),
    )

    args = parser.parse_args(argv)

    if args.cmd == "list-kinds":
        for kind in list_kinds():
            print(kind)
        return 0

    try:
        body = build(
            args.issue,
            agent=args.agent,
            session_url=args.session_url,
            model=args.model,
            kind=args.kind,
            include_footer=args.include_footer,
            template_path=Path(args.template),
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
