#!/usr/bin/env python3
"""Template-fill helper: emit a valid PR body skeleton from PULL_REQUEST_TEMPLATE.md.

Reads ``.github/PULL_REQUEST_TEMPLATE.md``, fills in the issue number, a
placeholder verification entry that satisfies the post-2026-05-26
command/result pair shape gate, and the agent attribution footer. The output
passes ``scripts/body_policy.py verify --kind pull_request --shape-cutoff
2026-05-26T00:00:00Z --body-file <path>`` so agents can start from a
policy-conformant skeleton instead of hand-rolling the shape.

Usage::

    python3 scripts/pr_body_builder.py build --issue 938
    python3 scripts/pr_body_builder.py build --issue 938 \\
        --agent "Claude Code" --session-url "https://claude.ai/code/session_XYZ"
    python3 scripts/pr_body_builder.py build --issue 938 \\
        --agent Codex --model gpt-4o

Refs #938.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from body_policy import build_codex_attribution_footer

REPO_ROOT = Path(__file__).resolve().parent.parent
_TEMPLATE_PATH = REPO_ROOT / ".github" / "PULL_REQUEST_TEMPLATE.md"

_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_CLOSES_PLACEHOLDER_RE = re.compile(r"^Closes #\s*$", re.MULTILINE)
_EMPTY_VERIFICATION_RE = re.compile(
    r"^(-[ \t]+command:[ \t]*``[ \t]*\n[ \t]{2}result:[ \t]*``[ \t]*)$",
    re.MULTILINE,
)
_FOOTER_PLACEHOLDER_RE = re.compile(
    r"_Generated by \[Agent Name\]\(agent-session-url\)_"
)

_DEFAULT_AGENT = "Claude Code"
_DEFAULT_SESSION_URL = "https://claude.ai/code"
_VERIFICATION_PLACEHOLDER = (
    "- command: `COMMAND`\n  result: `RESULT`"
)


def _build_footer(agent: str, session_url: str, model: str | None) -> str:
    """Return the attribution footer line for the given agent."""
    if agent.strip().lower() == "codex":
        if not model:
            raise ValueError(
                "Codex attribution requires --model; "
                "e.g. --model gpt-4o"
            )
        return build_codex_attribution_footer(model)
    return f"_Generated by [{agent}]({session_url})_"


def build(
    issue: int,
    *,
    agent: str = _DEFAULT_AGENT,
    session_url: str = _DEFAULT_SESSION_URL,
    model: str | None = None,
    template_path: Path = _TEMPLATE_PATH,
) -> str:
    """Return a PR body skeleton with *issue*, agent footer, and verification placeholder filled in.

    The returned string passes ``body_policy.verify`` with the post-2026-05-26
    shape gate enabled once the placeholder sections (Summary, Facts,
    Assumptions, Risk, Rollback, Verification command/result) are replaced with
    real content.
    """
    raw = template_path.read_text(encoding="utf-8")

    # Strip HTML comments -- they are for human template readers, not for
    # the body policy parser, and keeping them clutters the generated body.
    body = _HTML_COMMENT_RE.sub("", raw)

    # Collapse sequences of more than two blank lines that HTML comment
    # removal often leaves behind.
    body = re.sub(r"\n{3,}", "\n\n", body)

    # Fill in the issue number.
    body = _CLOSES_PLACEHOLDER_RE.sub(f"Closes #{issue}", body)

    # Replace bare dash bullets left by the template (content placeholders)
    # with "TBD" so the skeleton passes verify_section_substantive_content.
    body = re.sub(r"^-\s*$", "- TBD", body, flags=re.MULTILINE)

    # Replace the template's empty command/result placeholders with
    # non-empty ones that satisfy the shape gate regex.
    body = _EMPTY_VERIFICATION_RE.sub(_VERIFICATION_PLACEHOLDER, body)

    # Replace the attribution footer placeholder.
    footer = _build_footer(agent, session_url, model)
    body = _FOOTER_PLACEHOLDER_RE.sub(footer, body)

    # Ensure the body ends with a single newline.
    return body.rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_build = sub.add_parser(
        "build",
        help=(
            "Emit a valid PR body skeleton for the given issue. "
            "Fill in the placeholder sections before creating the PR."
        ),
    )
    p_build.add_argument(
        "--issue",
        type=int,
        required=True,
        help="Issue number to reference (Closes #<number>).",
    )
    p_build.add_argument(
        "--agent",
        default=_DEFAULT_AGENT,
        help=(
            f"Agent name for the attribution footer (default: {_DEFAULT_AGENT!r}). "
            "Use 'Codex' together with --model for the Codex-specific footer."
        ),
    )
    p_build.add_argument(
        "--session-url",
        default=_DEFAULT_SESSION_URL,
        help=(
            f"Session URL for the attribution footer "
            f"(default: {_DEFAULT_SESSION_URL!r}). "
            "Not used when --agent Codex is given."
        ),
    )
    p_build.add_argument(
        "--model",
        default=None,
        help="Codex model identifier (required when --agent Codex).",
    )
    p_build.add_argument(
        "--template",
        default=str(_TEMPLATE_PATH),
        help="Path to the PR body template (default: .github/PULL_REQUEST_TEMPLATE.md).",
    )

    args = parser.parse_args(argv)

    try:
        body = build(
            args.issue,
            agent=args.agent,
            session_url=args.session_url,
            model=args.model,
            template_path=Path(args.template),
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
