#!/usr/bin/env python3
"""Deterministic gate: the scripts/*.py size distribution snapshot stays current.

Refs #1701. The module-size gate (``scripts/scan_maintainability_metrics.py``,
#200) fails modules over the 800-line budget and warns on modules in the
``[640, 800]`` band (#1700). Those are per-run signals; this gate persists the
*distribution* so clustering near the budget is observable across git history
rather than only inside a single CI run.

``.gitapex/module-size-distribution.toml`` is the committed snapshot: an
aggregate histogram plus warn-band and over-budget membership. It holds counts
and module names, not per-module line counts, so an edit that does not cross a
bucket or band boundary leaves it unchanged (low churn) while a module entering
the warn band, crossing the budget, or shifting a histogram bucket shows up as a
reviewable diff. The git history of this one file is the time series.

The snapshot is generated, never hand-written:

- ``write`` regenerates ``.gitapex/module-size-distribution.toml``.
- ``verify`` regenerates in memory and compares; exit 1 on drift with an
  ``::error`` annotation telling the author to run ``write`` and commit.

Refs #2013: this snapshot follows the single-producer model of the
``docs/generated/`` tree (#1540/#1543/#1546). The post-merge ``decision-tree``
job in ``.github/workflows/post-merge.yml`` runs ``write`` and folds the result
into the ``chore/update-generated-docs`` PR; the post-merge ``verify-docs-drift``
gate runs ``write`` and fails on drift. The PR and pre-push gates no longer
regenerate it, so feature branches never touch the snapshot.

Architecture: pure functions (:func:`bucket_counts`, :func:`render_snapshot`)
on top, a single IO boundary at the bottom (:func:`_cmd_write`,
:func:`_cmd_verify`). Reuses :func:`find_module_sizes` so the two gates share
one measurement and cannot disagree about a module's size.

Contract:
- Inputs: the ``write`` or ``verify`` subcommand; ``--repo-root`` (defaults to
  the current directory, whose ``scripts/`` tree is measured).
- Outputs: ``write`` rewrites the snapshot and prints an ``OK`` line; ``verify``
  prints ``OK`` on a match or an ``::error::`` annotation on stderr on drift.
  Exit 0 on success, exit 1 when the committed snapshot is stale.
- Failure policy: fails loud per CLAUDE.md section 4 (it is a CI gate; drift or
  a regenerate failure exits non-zero).

Tested by ``tests/test_scan_module_size_distribution.py``. Refs #200, #1700, #1701, #2342.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from scan_maintainability_metrics import (
    MAX_MODULE_LINES,
    WARN_MODULE_LINES,
    ModuleSize,
    find_module_sizes,
)

SNAPSHOT_PATH = Path(".gitapex/module-size-distribution.toml")

# Histogram bucket upper edges (inclusive). A module's line_count lands in the
# first bucket whose edge it does not exceed; counts above the last edge fall in
# the overflow bucket. Edges align to the 640-line warn threshold and the
# 800-line budget so warn-band and over-budget transitions are visible in the
# histogram as well as in the summary counts.
BUCKET_EDGES = (160, 320, 480, 640, 800)


def bucket_label(index: int) -> str:
    """Return the inclusive line-range label for histogram bucket *index*."""
    lower = 1 if index == 0 else BUCKET_EDGES[index - 1] + 1
    if index < len(BUCKET_EDGES):
        return f"{lower}-{BUCKET_EDGES[index]}"
    return f"{BUCKET_EDGES[-1] + 1}+"


def bucket_counts(modules: list[ModuleSize]) -> list[int]:
    """Return the per-bucket module counts in :data:`BUCKET_EDGES` order."""
    counts = [0] * (len(BUCKET_EDGES) + 1)
    for module in modules:
        index = len(BUCKET_EDGES)
        for i, edge in enumerate(BUCKET_EDGES):
            if module.line_count <= edge:
                index = i
                break
        counts[index] += 1
    return counts


def _rel_names(modules: list[ModuleSize]) -> list[str]:
    return sorted(module.path.as_posix() for module in modules)


def _render_string_array(name: str, values: list[str]) -> list[str]:
    if not values:
        return [f"{name} = []"]
    lines = [f"{name} = ["]
    lines.extend(f'    "{value}",' for value in values)
    lines.append("]")
    return lines


def render_snapshot(modules: list[ModuleSize]) -> str:
    """Render the canonical TOML distribution snapshot for *modules*."""
    warn_band = [module for module in modules if module.is_in_warn_band]
    over_budget = [module for module in modules if module.is_over_budget]
    at_limit = [module for module in modules if module.line_count == MAX_MODULE_LINES]
    counts = bucket_counts(modules)

    lines: list[str] = [
        "# Generated by scripts/scan_module_size_distribution.py; do not edit by hand.",
        "# Regenerate: uv run python scripts/scan_module_size_distribution.py write",
        "# Tracks the scripts/*.py physical-line size distribution so clustering near",
        "# the line budget is observable across git history. Refs #1701.",
        "",
        "[budget]",
        f"max_module_lines = {MAX_MODULE_LINES}",
        f"warn_module_lines = {WARN_MODULE_LINES}",
        "",
        "[summary]",
        f"total_modules = {len(modules)}",
        f"in_warn_band = {len(warn_band)}",
        f"exactly_at_limit = {len(at_limit)}",
        f"over_budget = {len(over_budget)}",
        "",
        "# Module counts by inclusive physical-line range.",
        "[histogram]",
    ]
    lines.extend(f'"{bucket_label(i)}" = {count}' for i, count in enumerate(counts))
    lines.extend(
        [
            "",
            "# warn_band: passing modules in [warn_module_lines, max_module_lines].",
            "# over_budget: modules above the budget (deferred legacy debt). Names",
            "# only, so edits within a band do not churn the snapshot.",
            "[modules]",
        ]
    )
    lines.extend(_render_string_array("warn_band", _rel_names(warn_band)))
    lines.extend(_render_string_array("over_budget", _rel_names(over_budget)))
    return "\n".join(lines) + "\n"


def _cmd_write(args: argparse.Namespace) -> int:
    repo_root = Path(args.repo_root).resolve()
    snapshot = render_snapshot(find_module_sizes(repo_root))
    path = repo_root / SNAPSHOT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(snapshot, encoding="utf-8")
    print(f"OK: wrote {SNAPSHOT_PATH}")
    return 0


def _cmd_verify(args: argparse.Namespace) -> int:
    repo_root = Path(args.repo_root).resolve()
    expected = render_snapshot(find_module_sizes(repo_root))
    path = repo_root / SNAPSHOT_PATH
    actual = path.read_text(encoding="utf-8") if path.exists() else None

    if actual == expected:
        print(f"OK: {SNAPSHOT_PATH} matches the current distribution.")
        return 0

    print(
        f"::error file={SNAPSHOT_PATH}::{SNAPSHOT_PATH} is stale: the "
        "scripts/*.py size distribution changed. Regenerate with "
        "'uv run python scripts/scan_module_size_distribution.py write' and "
        "commit the result.",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_write = sub.add_parser(
        "write", help="Regenerate the committed size-distribution snapshot."
    )
    p_write.add_argument("--repo-root", default=".")
    p_write.set_defaults(func=_cmd_write)

    p_verify = sub.add_parser(
        "verify", help="Fail when the committed snapshot is stale."
    )
    p_verify.add_argument("--repo-root", default=".")
    p_verify.set_defaults(func=_cmd_verify)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
