#!/usr/bin/env python3
"""Verify no prose double-hyphen separator appears in tracked repository files.

Issue #1903 (follow-up to #1899/#1902, PR #1900): those changes eliminated
space-hyphen-hyphen-space prose separators from
``.apm/instructions/master.instructions.md`` and its compiled artifacts.
The remaining tracked files still carry the pattern with no deterministic
gate; an agent editing any of those files can reintroduce it without a CI
failure. This script is the re-entry gate.

Invoked from ``verify-pr.yml`` (portable-pr-policy job) and registered in
``preflight_steps.py`` as::

    python3 scripts/scan_repo_double_hyphen.py verify --git-tracked

The contract is:

* ``--git-tracked`` enumerates all files known to git (``git ls-files``) and
  scans each one, excluding paths in ``_SKIP_PREFIXES`` and files whose
  extension is in ``_SKIP_EXTENSIONS`` (DSL files where the separator pattern
  is syntax, not prose). Files whose UTF-8 decoding fails are skipped with a
  notice (never a failure; the scan is about the pattern, not about encoding).
* ``--path`` adds one explicit path; repeatable. May be combined with
  ``--git-tracked`` (paths are unioned and de-duplicated). Explicit ``--path``
  targets are not filtered by ``_SKIP_PREFIXES`` or ``_SKIP_EXTENSIONS``.
* Every occurrence of ``_DOUBLE_HYPHEN`` is a violation unless the containing
  line is excluded by ``_should_skip_line``:
    - Lines containing ``# noqa:`` (ruff/flake8 suppression annotations carry
      the separator in their inline rationale by convention and MUST NOT be
      altered).
    - Lines containing ``# dh-ok`` (project-local gate-suppress marker for
      intentional non-prose uses such as git end-of-options syntax; use when
      ``# noqa:`` would trigger RUF100 because there is no Ruff violation).
  There is no other allowlist: use ASCII punctuation (semicolon, comma, or
  parentheses) as the substitute in every prose context this repository uses
  (comments, docstrings, Markdown prose, including table cells).
* Exit 0 when every scanned file is clean; exit 1 on any violation; exit 2
  when neither ``--git-tracked`` nor ``--path`` is supplied. Each hit emits
  ``::error file=<path>,line=<n>,col=<c>::...`` on stderr so the GitHub
  Actions UI surfaces individual violations.

Excluded path prefixes (``_SKIP_PREFIXES``):
    ``.agents/skills/``: files expanded from the APM upstream dependency
        (``obra/superpowers`` pinned in ``apm.yml``). These files must not be
        edited directly; any such content there originates upstream and is
        outside this repo's fix scope.
    ``docs/archive/``: frozen historical documents; not maintained by this
        repo's change process.
    ``docs/generated/``: auto-generated by post-merge CI; hand-editing is
        forbidden, so prose style is outside this gate's scope.

Excluded file extensions (``_SKIP_EXTENSIONS``):
    ``.yml``, ``.yaml``: workflow and config files where ``--`` is valid YAML
        comment or flag syntax (e.g. ``actionlint --shellcheck``).
    ``.sh``: shell scripts where ``--`` terminates option processing.
    ``.json``, ``.toml``, ``.lock``, ``.sql``: structured data formats where
        the pattern could appear in values outside this gate's prose scope.

Contract:
    Inputs: the ``verify`` subcommand plus ``--git-tracked`` and/or one or
        more ``--path`` arguments. No stdin, no environment variables.
    Outputs: ``::error file=<path>,line=<n>,col=<c>::`` annotation on stderr
        for each hit (excluding skipped lines), plus an ``OK:`` /
        ``FAIL:`` summary line; exit 0 when every scanned file is clean,
        1 on any violation, 2 when no scan targets are supplied.
    Failure policy: fails loud per CLAUDE.md section 4; a double-hyphen prose
        separator or a ``git ls-files`` failure exits non-zero rather than
        passing silently.

Tested by ``tests/test_scan_repo_double_hyphen.py``. Refs #1903.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Defined by concatenation so this source file does not contain the literal
# space-hyphen-hyphen-space sequence and does not flag itself.
_DOUBLE_HYPHEN = " " + "--" + " "

_SKIP_PREFIXES = (
    ".agents/skills/",
    "docs/archive/",
    "docs/generated/",
)

_SKIP_EXTENSIONS = {
    ".yml",
    ".yaml",
    ".sh",
    ".json",
    ".toml",
    ".lock",
    ".sql",
}


def _should_skip_line(line: str) -> bool:
    """Return True when *line* must not be scanned for the double-hyphen pattern.

    Excluded line classes:
    - Lines containing ``# noqa:`` (ruff/flake8 inline suppression comments
      conventionally carry the separator in their rationale; altering them
      would break the suppression syntax or lose context).
    - Lines containing ``# dh-ok`` (project-local gate-suppress marker for
      intentional non-prose uses such as git end-of-options syntax; use when
      ``# noqa:`` would trigger RUF100 because there is no Ruff violation).
    """
    return "# noqa:" in line or "# dh-ok" in line


def scan_text(text: str) -> list[tuple[int, int]]:
    """Return ``(line, column)`` for every double-hyphen separator in *text*.

    Line and column numbers are 1-based to match GitHub Actions
    ``::error file=`` annotations and an editor's cursor.

    The function is pure (it never touches the filesystem); so the
    detection is unit-tested directly on string fixtures.
    """
    hits: list[tuple[int, int]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if _should_skip_line(line):
            continue
        start = 0
        while True:
            idx = line.find(_DOUBLE_HYPHEN, start)
            if idx == -1:
                break
            hits.append((lineno, idx + 1))
            start = idx + len(_DOUBLE_HYPHEN)
    return hits


def scan_file(path: Path) -> list[tuple[int, int]]:
    """Return ``(line, column)`` for every double-hyphen separator in *path*.

    Returns an empty list and prints a notice when the file cannot be decoded
    as UTF-8 (binary files) or when the path is a directory.
    """
    try:
        return scan_text(path.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, IsADirectoryError, OSError):
        print(f"notice: skipping {path} (unreadable as UTF-8)")
        return []


def _git_tracked_files() -> list[Path] | None:
    """Return git-tracked files, excluding paths and extensions in skip sets.

    Returns ``None`` (and emits an ``::error::`` annotation) when
    ``git ls-files`` fails; the caller must treat ``None`` as a hard
    error rather than an empty file list, so the gate never silently
    passes when it cannot enumerate the repository.
    """
    result = subprocess.run(  # noqa: S603 -- fixed argv, shell=False
        ["git", "ls-files"],  # noqa: S607 -- git resolved via PATH
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(
            f"::error::git ls-files failed: {result.stderr.strip()}",
            file=sys.stderr,
        )
        return None
    return [
        Path(p)
        for p in result.stdout.splitlines()
        if p
        and not any(p.startswith(prefix) for prefix in _SKIP_PREFIXES)
        and Path(p).suffix not in _SKIP_EXTENSIONS
    ]


def _verify(paths: list[Path]) -> int:
    total = 0
    for path in sorted({p for p in paths if p.is_file()}):
        for lineno, column in scan_file(path):
            print(
                f"::error file={path},line={lineno},col={column}::"
                f"prose{_DOUBLE_HYPHEN}separator found. Replace with ASCII punctuation"
                " (semicolon, comma, or parentheses). Refs #1903.",
                file=sys.stderr,
            )
            total += 1
    if total:
        print(
            f"FAIL: {total} double-hyphen prose separator violation(s).",
            file=sys.stderr,
        )
        return 1
    print(f"OK: no prose{_DOUBLE_HYPHEN}separator found in scanned files.")
    return 0


def _cmd_verify(args: argparse.Namespace) -> int:
    if not args.git_tracked and not args.path:
        print(
            "error: supply --git-tracked or at least one --path",
            file=sys.stderr,
        )
        return 2
    paths: list[Path] = [Path(p) for p in args.path]
    if args.git_tracked:
        tracked = _git_tracked_files()
        if tracked is None:
            return 1
        paths.extend(tracked)
    return _verify(paths)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_verify = sub.add_parser(
        "verify",
        help="Scan for prose double-hyphen separator in tracked repository files.",
    )
    p_verify.add_argument(
        "--git-tracked",
        action="store_true",
        default=False,
        help="Scan all files enumerated by `git ls-files`.",
    )
    p_verify.add_argument(
        "--path",
        action="append",
        default=[],
        help="Explicit path to scan. Repeatable; may be combined with "
        "--git-tracked.",
    )
    p_verify.set_defaults(func=_cmd_verify)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
