#!/usr/bin/env python3
"""Verify docs lane inventory and top-level placement.

Refs #918. ``docs/INDEX.md`` is the operator-facing map for the docs
tree, so every Markdown document under ``docs/`` must either appear
there or be the index itself. Top-level docs are reserved for navigation
and documented compatibility pointers.

Refs #1665. Because INDEX is read on demand during navigation, this gate
also enforces a byte budget on it (``MAX_INDEX_BYTES``) so its growth is
blocked rather than discovered.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = Path("docs/INDEX.md")
ALLOWED_TOP_LEVEL_DOCS = frozenset(
    {
        "docs/INDEX.md",
        "docs/agent-provenance.md",
    }
)
# Directories whose Markdown is owned by automation and exempt from the
# per-file INDEX linking requirement. Both hold one auto-generated doc per
# source object, regenerated by the post-merge automation and protected from
# manual edits by scripts/gate_generated_scripts_manual_edit.py; listing each
# file in docs/INDEX.md would drift as the source objects are added or removed,
# so each directory is described once in INDEX and skipped here.
# - docs/generated/scripts/ holds one AST/dependency/trigger doc per script (#1540).
# - docs/generated/workflows/ holds one if-branch diagram per workflow (#1613).
EXEMPT_INVENTORY_PREFIXES = (
    "docs/generated/scripts/",
    "docs/generated/workflows/",
)

INLINE_LINK_RE = re.compile(r"!?\[[^\]\n]*\]\(([^)\n]+)\)")
REFERENCE_LINK_RE = re.compile(r"^\s{0,3}\[[^\]\n]+\]:\s+(\S+)", re.MULTILINE)
IGNORED_SCHEMES = frozenset({"http", "https", "mailto", "tel", "data"})

# Refs #1665. docs/INDEX.md is read on demand whenever an agent navigates
# docs/ (it is not part of the per-request prefix), so its byte weight is a
# per-navigation read cost. This budget caps that cost so runaway growth is
# blocked rather than discovered, and the decision to split INDEX into
# per-lane sub-indexes is forced at a documented threshold rather than left
# to agent memory. The ceiling (40 KiB) sits above the current size (~31.5
# KiB at adoption) with headroom for near-term lane additions; the
# remediation when it trips is the per-lane split documented in
# docs/standards/documentation-quality.md (D3), not a budget bump.
MAX_INDEX_BYTES = 40 * 1024


def rel(path: Path, root: Path) -> str:
    """Return a stable repository-relative path string."""
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def extract_target(raw: str) -> str:
    """Return the URL/path portion of a Markdown link target."""
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        return target[1 : target.index(">")]
    if " " in target:
        return target.split(" ", 1)[0]
    return target


def iter_docs_markdown(root: Path) -> list[Path]:
    """Return every Markdown document below ``docs/``."""
    docs = root / "docs"
    if not docs.exists():
        return []
    return sorted(path for path in docs.rglob("*.md") if path.is_file())


def collect_index_entries(root: Path) -> set[str]:
    """Return repository-relative docs paths linked from ``docs/INDEX.md``."""
    index = root / INDEX_PATH
    if not index.exists():
        return set()

    text = index.read_text(encoding="utf-8")
    entries: set[str] = set()
    for pattern in (INLINE_LINK_RE, REFERENCE_LINK_RE):
        for match in pattern.finditer(text):
            target = extract_target(match.group(1))
            parts = urlsplit(target)
            if parts.scheme in IGNORED_SCHEMES or target.startswith("//"):
                continue
            raw_path = unquote(parts.path)
            if not raw_path or raw_path == ".":
                continue
            if Path(raw_path).is_absolute():
                resolved = root / raw_path.lstrip("/")
            else:
                resolved = index.parent / raw_path
            if resolved.suffix.lower() == ".md":
                entries.add(rel(resolved.resolve(), root.resolve()))
    return entries


def verify_index_budget(root: Path) -> list[str]:
    """Return a budget diagnostic when ``docs/INDEX.md`` exceeds the ceiling.

    The byte count, not the line count, is the navigation read cost: a few
    verbose table rows cost more than many terse ones, so bytes are the
    faithful signal here. Over budget, the fix is to split INDEX into
    per-lane sub-indexes (see ``docs/standards/documentation-quality.md``
    D3), which also requires teaching this gate to follow links
    transitively; a budget bump is not the remediation.
    """
    index = root / INDEX_PATH
    if not index.exists():
        return []
    size = index.stat().st_size
    if size <= MAX_INDEX_BYTES:
        return []
    return [
        f"::error file={INDEX_PATH.as_posix()}::docs/INDEX.md is {size} bytes, "
        f"over the {MAX_INDEX_BYTES}-byte navigation budget; split it into "
        "per-lane sub-indexes (docs/standards/documentation-quality.md D3) "
        "rather than raising the budget"
    ]


def verify(root: Path = REPO_ROOT) -> list[str]:
    """Return docs inventory diagnostics."""
    root = root.resolve()
    errors: list[str] = verify_index_budget(root)
    index_entries = collect_index_entries(root)

    for path in iter_docs_markdown(root):
        relative = rel(path, root)
        if any(relative.startswith(prefix) for prefix in EXEMPT_INVENTORY_PREFIXES):
            continue
        if path.parent == root / "docs" and relative not in ALLOWED_TOP_LEVEL_DOCS:
            errors.append(
                f"::error file={relative}::unexpected top-level docs file; "
                "move it into a lane or add an explicit compatibility exemption"
            )
        if relative == INDEX_PATH.as_posix():
            continue
        if relative not in index_entries:
            errors.append(
                f"::error file={INDEX_PATH.as_posix()}::docs/INDEX.md "
                f"does not list {relative}"
            )
    return errors


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("verify", help="verify docs inventory")
    args = parser.parse_args(argv)

    if args.command == "verify":
        errors = verify(REPO_ROOT)
        for error in errors:
            print(error, file=sys.stderr)
        return 1 if errors else 0
    parser.error(f"unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
